### ISSUE TITLE
render the graph with the rate

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#100]
Let's show the graph.

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#100` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
