### ISSUE TITLE
/rate in user menu

### ISSUE THREAD

**Issue by blackout314** [zold-io/wts.zold.io#101]
we miss a simple link of rate in menu
<img width="554" alt="screen shot 2019-01-09 at 15 59 37" src="https://user-images.githubusercontent.com/818568/50907500-d5842c80-1427-11e9-8ace-b4506d041825.png">

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@blackout314 fixed in 97fd9cf thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#101` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
