### ISSUE TITLE
missing hosting bonus payment

### ISSUE THREAD

**Issue by n4kashu** [zold-io/wts.zold.io#104]
Hey, 

I believe i'm missing one hosting bonus payment:

ID | Amount | Date | From/To | Details
- | 0.20 | 11m | e5b5fc7379d80ed7 | Hosting bonus for 104.227.245.154 4096 42
- | 0.17 | 1h | e5b5fc7379d80ed7 | Hosting bonus for 104.227.245.154 4096 40
- | 0.33 | 3h | e5b5fc7379d80ed7 | Hosting bonus for 104.227.245.154 4096 35
- | 0.20 | 4h | e5b5fc7379d80ed7 | Hosting bonus for 104.227.245.154 4096 31

nothing critical but as you instructed in the blog, im reporting..

**Comment by yegor256** [comment]
@n4kashu you are not supposed to get them every hour. They are distributed randomly among _some_ available nodes. I explained better in the blog: https://github.com/zold-io/blog.zold.io/commit/93f1e4970f2c8f6f6ab0485e4a3e33f388ae3bae

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#104` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by n4kashu** [comment]
I understood it the way that it is based on score the node has and 8 best scoring nodes with score above some treshold(score>4??) is getting the reward paid.. my node 104.227.245.154:4096 is on top, currently it has the best score since several hours.. following this logic it is weird that it does not get paid as it is ,by the metrics you have set, the best performing POW on the network.. do I miss something? 
--

**Comment by n4kashu** [comment]
oh I can see now on the telegram channel that there was no reward paid that hour to anybody..
