### ISSUE TITLE
hosting bonus payment missing

### ISSUE THREAD

**Issue by n4kashu** [zold-io/wts.zold.io#106]
There was no payment of hosting bonuses yesterday(2019-01-10) at 10 and 14 am as per telegram channel.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@n4kashu[/z](https://www.0crat.com/u/n4kashu) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.3`

**Comment by yegor256** [comment]
@n4kashu should be fine now, thanks for reporting

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#106` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by n4kashu** [comment]
just to let you know that it is not working at all since the release.. :P
