### ISSUE TITLE
issue #106 fix not working at all..

### ISSUE THREAD

**Issue by n4kashu** [zold-io/wts.zold.io#108]
hi. seems like the version you have pushed to fix issue #106 is not working at all. no reward at all paid since deployment.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@n4kashu[/z](https://www.0crat.com/u/n4kashu) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@n4kashu 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#108` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
