### ISSUE TITLE
broken - nothing works

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/wts.zold.io#11]
Version is `0.0.0` and `0` wallets loaded.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@oltdaniel what exactly doesn't work? Try to click `pull`.

**Comment by oltdaniel** [comment]
I had an complete error that notging could be reached.

But everything works again.
