### ISSUE TITLE
How to get apikey from keygap using API?

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/wts.zold.io#111]
The API documentation doesn't mention how to get the API key using key gap
I think it's by sending the key gap as a post request to do-API-token
It should be added.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ammaratef45 it seems to be impossible. You have to be logged in before you get the API token.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#111` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
