### ISSUE TITLE
Invoice API

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#116]
To implement 0crat project funding with ZLD (https://github.com/zerocracy/farm/issues/1858) we need to be able to generate unique invoice for each funding operation and check the balance recceived on this invoice.

I see this flow as:
 1. User clicks on "fund with ZLD" button
 2. 0crat asks wts API to generate new invoice address, save it, and returns it to the user
 3. User send some amount of Zold to this invoice address
 4. 0crat periodaclly checks the balance of this invoice and if it was changed, update projects ledger and stop watching for this invoice.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 I would suggest a different scenario:

1. 0crat gets a new invoice via `/invoice.json` URL (I will implement it)
2. 0crat registers a callback: `/wait-for?invoice=PREFIX&details=text&callback=https://www.0crat.com/zold`
3. Once a payment arrives to invoice `PREFIX` with `text` in the details, WTS sends GET request to `https://www.0crat.com/zold?wallet=...&txn=123&amount=54.00`
4. 0crat responds with 200. 
5. If 0crat responds with anything else, WTS keeps sending GET request for 24 hours, until it gets 200

WDYT? This is how blockchain.com works, I just copied their protocol.

**Comment by g4s8** [comment]
@yegor256 yes, it looks easier, but with such implementation we have to ensure that callback was sent by wts, it may be done if wts will add a signature header of the callback HTTP request (usually request query includes random nonce and a timestamp to generate unique signatures and validate by time), e.g. using hmac-sha256 with secret key.

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.0`

**Comment by yegor256** [comment]
@g4s8 it's implemented. The documentation is here: https://github.com/zold-io/wts.zold.io#callback-api I will test it thoroughly tomorrow.

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.1`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#116` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@yegor256 is it possible to verify that callback was called by wts and not by knowing person? Maybe wts can provide a signature for callback payload that can be verified with some public key?

**Comment by yegor256** [comment]
@g4s8 you are right. We should allow the user to send us a secret token when creating the callback. And then, we return that token back. Please, create a ticket.
