### ISSUE TITLE
BTC payments are not received

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#123]
Some issue with blockchain.com, I believe...

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.12`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.14`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.15`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#123` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by merobero** [comment]
https://github.com/yegor256/elegantobjects.github.io/issues/3#issuecomment-470848926
