### ISSUE TITLE
mobile registration API

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#126]
Let's add these entry points:

`GET /mobile/send?phone=+15551234567`: returns `200` if the SMS has been sent to the user with the authentication code.

`GET /mobile/token?phone=+15551234567&code=6666`: returns API access token. The `code` is the code from the SMS.

Both requests must have `app=1234567` parameter with the mobile app ID (which is a secret).

**Comment by ammaratef45** [comment]
@yegor256 how will you make sure that the phone number belongs to the wallet's owner?
I guess you intend to use the `app=1234567` as an authorization way. so, if this is the case, how the app ID will be generated and distributed?

**Comment by yegor256** [comment]
@ammaratef45 there will be no connection between GitHub-based accounts in WTS and mobile accounts. There are two types of accounts.

**Comment by ammaratef45** [comment]
@yegor256 So, anyone has access to the phone owns the account?

**Comment by yegor256** [comment]
@ammaratef45 correct

**Comment by yegor256** [comment]
@ammaratef45 this is implemented already, you can try how it works (try in 12 hours)

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#126` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by ammaratef45** [comment]
@yegor256 
I tried `mobile/send?phone=+201153300223` and I got `Invalid phone "+201153300223"`


I tried to replace + with 00 then I got an internal error with the following log

> RuntimeError: There is no item in DynamoDB for @00201153300223
> 	/app/objects/item.rb:188:in `read'
> 	/app/objects/item.rb:121:in `mcode_set'
> 	/app/wts.rb:704:in `block in <top (required)>'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
> 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
> 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
> 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
> 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
> 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
> 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
> 	/app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
> 	/app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
> 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
> 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/handler/thin.rb:22:in `run'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:297:in `start'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
> 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
> 	/app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `load'
> 	/app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `<top (required)>'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
> 	/app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
> 	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
> 	/app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
> 	/app/vendor/bundle/bin/bundle:104:in `load'
> 	/app/vendor/bundle/bin/bundle:104:in `<main>'

**Comment by ammaratef45** [comment]
@yegor256 the invalid phone message still there
