### ISSUE TITLE
Support bech32 addresses for btc transfer

### ISSUE THREAD

**Issue by victornoel** [zold-io/wts.zold.io#127]
One of the most used btc client, electrum, only support Bech32 addresses (see for example: https://www.reddit.com/r/Bitcoin/comments/7wjknp/electrum_address_starts_with_bc1_but_this_isnt/).

The currently supported formats are, according to the `/btc` page:
> Bitcoin address to send to, in P2PKH or P2SH format:

It would make sense to be able to transfer ZLD to BTC via the use of a Bech32 address.
Those addresses are the one starting with `bc1...` while `P2PKH` starts with `1...` and P2SH with `3...` (see https://en.bitcoin.it/wiki/Address).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@victornoel what is the regex we should allow?

**Comment by victornoel** [comment]
@yegor256 do you mean the regex for preventing Bech32 address to be used?

**Comment by yegor256** [comment]
@victornoel the regex we should accept in the form

**Comment by victornoel** [comment]
@yegor256 I have updated the description to be more clear about the bug.

**Comment by victornoel** [comment]
@yegor256 if you want to validate P2SH and P2PKH addresses, you can use those regex: http://mokagio.github.io/tech-journal/2014/11/21/regex-bitcoin.html

**Comment by victornoel** [comment]
@yegor256 that being said, as explained at the end of this link, it would be better to really validate the address with checksum

**Comment by victornoel** [comment]
@yegor256 but this is out of scope of this issue :)

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.17`

**Comment by yegor256** [comment]
@victornoel indeed, let's make a separate ticket for better/stronger validation of bitcoin addresses. Our current regex is primitive.

**Comment by 0crat** [comment]
The job [#127](https://github.com/zold-io/wts.zold.io/issues/127) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB28FH2NR/a06e6d73-b23d-4cc2-bf8a-de9a854fd7e7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#127` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by yegor256** [comment]
@victornoel this one is fixed in da77929 thanks!

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#127](https://github.com/zold-io/wts.zold.io/issues/127) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
