### ISSUE TITLE
Mock API key for testing

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/wts.zold.io#130]
Do we have a testing network so that I can write unit testing using safely available public wallets?
What else can be done if no?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ammaratef45 you can just create a new account, send yourself a few ZLD and experiment with that. That's the best we can do.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#130` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
