### ISSUE TITLE
Exchange rates for Zerocracy users

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#131]
I think we can make lower exchange fee for 0crat users as suggested in https://github.com/zerocracy/farm/issues/1860#issuecomment-463672893 (from 8% to 2%) so we will take this 2% from payer project as payment fee and add +2% to user's payments with ZLD wallets.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 fixed in e94d139

**Comment by yegor256** [comment]
@g4s8 you can check it online, your rate should be 2% now.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#131` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
