### ISSUE TITLE
Auto-exchange configuration

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#132]
To makes it easier to Zerocracy users to get cash from 0crat with ZLD payments, wts can add auto-exchange option for new payments. E.g. user may set BTC address and all new ZLD payments will be exchanged to BTC and sent to this address.
I think it should not affect existing ZLD (which was received before user configured auto-exchange).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@04b23b23-d6ff-4467-8f09-32f25319699c, thread: pool-292-thread-1
com.jcabi.github.RtValuePagination$Items[181] java.lang.IllegalStateException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.41.1](https://github.com/zerocracy/farm): Issue: zold-io/wts.zold.io#132, Action: `created`

**Comment by yegor256** [comment]
@g4s8 even though it's a good idea, it seems to be too dangerous... Let's not do this.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#132` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
