### ISSUE TITLE
BTC addresses are lost

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#134]
We lose them when we swap

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#134` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
