### ISSUE TITLE
/general-ledger

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#137]
Let's create a system to collect all ledger updates from all visible nodes and put all transactions into one table.

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#137` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
