### ISSUE TITLE
No payment id on pay

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#139]
Payment API doesn't return any payment-id on success, so it's not possible to track some payment failures. See https://github.com/zerocracy/farm/issues/1901

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@yegor256 See zerocracy/farm#1901 , a payment of  $70 was lost

**Comment by yegor256** [comment]
@g4s8 you should get the ID of the job via `X-Zold-Job` HTTP header in the response. That can be used later to check the status of the job and see the logs: https://github.com/zold-io/wts.zold.io#api Is it what you are doing?

**Comment by yegor256** [comment]
@g4s8 see how the Ruby SDK work: https://github.com/zold-io/zold-ruby-sdk After each payment you "wait" for the job to complete, checking the `/job` page to return `OK`.

**Comment by g4s8** [comment]
@yegor256 got it, thanks

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#139` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
