### ISSUE TITLE
balance API returns HTML not JSON

### ISSUE THREAD

**Issue by amorenew** [zold-io/wts.zold.io#140]
I have tried
https://wts.zold.io/balance
on Postman with headers
Content-Type: "application/x--form-urlencoded"
X-Zold-Wts: "My private user Id"
 but I got the response as HTML why we don't get the response as JSON ?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@amorenew when I open that URL I get a number. Most likely you are not logged in or something else is wrong. First, check the response code. If it's not 200, check `X-Zold-Error` header -- it will explain the problem.

**Comment by amorenew** [comment]
@amorenew now I got a number but I clicked on my wallet "Pull it from the network"
in documentation 

> GET /pull: asks the server to pull your wallet from the network.

Why we need to pull wallet I think when we query balance it should auto pull the wallet right?

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#140` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by amorenew** [comment]
related PR https://github.com/zold-io/wts.zold.io/pull/142
