### ISSUE TITLE
/job API documentation is not clear

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#141]
API docs says:
> GET /job: checks the status of the jobs, expecting id argument. Returns OK if the job is completed, otherwise a full log of its execution.

It's not clear what is "id argument", is it a part of url path, or query param, or something else?
Also it doesn't say about response status codes: does API returns 200 code if job was not completed? what status API returns in case of error?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 see 1ff1c19

**Comment by 0crat** [comment]
This job is not in scope
