### ISSUE TITLE
/balance returns 200 status even if wallet needs to be pulled

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/wts.zold.io#145]
Balance endpoint should return non-200 response if the wallet needs to be pulled.
Currently, it returns 200 with the HTML page prompting to pull it.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ammaratef45 how do you check?) It returns 302, but your browser redirects you to `/home`

**Comment by ammaratef45** [comment]
@yegor256 Yes sorry, forgot to disable automatic follow redirect

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#145` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
