### ISSUE TITLE
Verify callbacks

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#147]
Callback receiver should be able to verify that callback was sent by wts server and not by someone else.
It can be done using callback signing https://github.com/zold-io/wts.zold.io/issues/116#issuecomment-466037798 or by providing secret token from user: https://github.com/zold-io/wts.zold.io/issues/116#issuecomment-466062091

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.2`

**Comment by yegor256** [comment]
@g4s8 I believe it's fixed.

**Comment by g4s8** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
The job [#147](https://github.com/zold-io/wts.zold.io/issues/147) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB28FH2NR/4376e18e-0f39-4394-b32b-6824eaa18462); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#147` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#147](https://github.com/zold-io/wts.zold.io/issues/147) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
