### ISSUE TITLE
Can't sell ZLD for two days

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#148]
I'm trying to sell some zold using "sell" button, but it says:
> At the moment we can send only one payment per day, sorry 

but previously I sold zold on `2019-02-20T11:39:27Z` and today is `2019-02-22`
my wallet is `3be3416c805e4371`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 the problem is that this check just validates when was the recent negative transaction from your wallet, no matter where it was sent. Let me see how this can be fixed. The easiest workaround at the moment is to Migrate.

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.0`

**Comment by yegor256** [comment]
@g4s8 try it, should work just fine.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#148` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@yegor256 thanks
