### ISSUE TITLE
Where is my 8 ZLD?

### ISSUE THREAD

**Issue by artem-p** [zold-io/wts.zold.io#15]
> Once you sign-up, you will receive a bonus of 8 ZLD to your wallet.

I've registered and my  Balance: 0.00ZLD.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@artem-p[/z](https://www.0crat.com/u/artem-p) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@artem-p did you try to `pull`? You should have it. Please, confirm.

**Comment by artem-p** [comment]
I did few times. Still 0.

**Comment by SilasReinagel** [comment]
@yegor256 I am experiencing the same issue.

**Comment by artem-p** [comment]
@yegor256  OK, it works after restart.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#15` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a3ae9e3a-5c55-4597-a751-c76188d0d54a, thread: pool-26-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "catalog.xml" in "PMO" in 1min: 5a7468575572/4min/0/2/true/false by QuartzScheduler_Worker-10
```

[0.22.11](https://github.com/zerocracy/farm): Issue: zold-io/wts.zold.io#15, Action: `reopened`

**Comment by yegor256** [comment]
@artem-p I believe this problem is fixed. If you see something like that again, open a new ticket pls.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b6bacaf1-6a1c-4350-8b12-c99321e58e43, thread: AsyncFlush-2
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zold-io/wts.zold.io#15] declared for identity constraint of element "blanks".
```

[0.23.3](https://github.com/zerocracy/farm): CID: [1780536135](https://www.0crat.com/CB28FH2NR/1780536135), Type: "Close job", Author: "yegor256"

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#15` is not assigned, can't get performer
