### ISSUE TITLE
Getting token with mobile API

### ISSUE THREAD

**Issue by vryazanov** [zold-io/wts.zold.io#150]
Hey, I'm actively using mobile API these days and there is one thing confuses me.

`GET /mobile/token?phone=+15551234567&code=6666`

This API returns response status 200 even the code is incorrect (and there is html in the body). I believe it should return 400 status.
Is there a way to understand that there is a token in the response without any hacks?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vryazanov[/z](https://www.0crat.com/u/vryazanov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@vryazanov it responds with 302 and your browser redirects automatically (or curl). Try it with:

```
curl -v https://wts.zold.io/mobile/token?phone=+15551234567&code=6666
```

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#150` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
