### ISSUE TITLE
Mobile api deson't confirm keygap automatically

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/wts.zold.io#155]
Hi Yegor,
I had this problem while testing the mobile API trying to get the balance of a wallet.

>303
I/flutter (23455): UserError: You, 201099903387, have to confirm your keygap first
I/flutter (23455):      /app/wts.rb:1068:in `confirmed_user'
I/flutter (23455):      /app/wts.rb:491:in `block in <top (required)>'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/handler/thin.rb:22:in `run'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:297:in `start'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `load'
I/flutter (23455):      /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `<top (required)>'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
I/flutter (23455):      /app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
I/flutter (23455):      /app/vendor/bundle/bin/bundle:104:in `load'
I/flutter (23455):      /app/vendor/bundle/bin/bundle:104:in `<main>'

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ammaratef45 I explained it here: f51a7c3

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#155` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
