### ISSUE TITLE
/payables

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#156]
Let's list all wallets and their balances in one page.

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#156` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
