### ISSUE TITLE
Job ID is not found

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#160]
0crat failed to pay because of error (origin error: https://sentry.io/organizations/zerocracy/issues/906997140/?project=193755&query=is%3Aunresolved&statsPeriod=14d&utc=false): 
```
Job ID 7c8353a6-3544-444c-b751-44523615da8b is not found
	/app/wts.rb:794:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatr...
```

It seems #143 bug was not fixed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 this may happen. Most likely because the server was restarted. When you sent the `do-pay` request, the job was started and you got the ID. Then, the server is terminated and you hit it again, when its memory is empty. Of course, the is no job anymore. I will try to fix it now by persisting job IDs in PostgreSQL.

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.4`

**Comment by yegor256** [comment]
@g4s8 shouldn't happen again. If it does, open a new ticket pls.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#160` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@yegor256 thanks
