### ISSUE TITLE
One zold payment is missing in wallet

### ISSUE THREAD

**Issue by ypshenychka** [zold-io/wts.zold.io#164]
I didn't receive actual payment for timelesslounge/timelessis#445.

Although it was mentioned on the chat
![image](https://user-images.githubusercontent.com/11703257/53720401-57f9fd00-3e69-11e9-8d68-47bb9e07718e.png)

I don't see it on the list in my wallet.
![image](https://user-images.githubusercontent.com/11703257/53720421-66481900-3e69-11e9-9c6e-aad9fdbe0cbc.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka try to "pull" it. Still not there?

**Comment by ypshenychka** [comment]
No, it's not there. I've got some "debt" payment two minutes ago. But I believe it's for two recently reviewed tickets (https://github.com/timelesslounge/timelessis/pull/427 and https://github.com/timelesslounge/timelessis/pull/401). So still nothing for #445.

![image](https://user-images.githubusercontent.com/11703257/53731423-5ccbaa80-3e83-11e9-93f1-0cbf7afd9c0e.png)

**Comment by yegor256** [comment]
@ypshenychka shouldn't happen any more, after this fix: 61d7b3d

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#164` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
