### ISSUE TITLE
WTS sell page: Mask keygap

### ISSUE THREAD

**Issue by pinaf** [zold-io/wts.zold.io#171]
Right now the keygap field in the WTS "sell zold" page is in plaintext.
Please mask it using asterisks like any other password field.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@pinaf[/z](https://www.0crat.com/u/pinaf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@pinaf fixed in f696538 thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#171` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
