### ISSUE TITLE
WTS sell page: Missing Bitcoin Transaction Hash

### ISSUE THREAD

**Issue by pinaf** [zold-io/wts.zold.io#172]
Whenever zold is successfully zold, the page displays a message as follows:
`We took XYZ ZLD from your wallet and sent you ZYX BTC`
However, no info is given on the actual BTC transaction generated which will, after some time, end up confirmed in a BTC block.

Please provide the BTC transaction hash on success to that the seller can track the transaction.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@pinaf[/z](https://www.0crat.com/u/pinaf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@pinaf the best we can do at the moment was done in 9b325b9 Once we migrate to our own Bitcoin adapter, we will show more details: #163

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#172` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
