### ISSUE TITLE
It's not clear how callbacks supposed to be used

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#173]
I see two ways of using callbacks API:
1. Client creates new invoice and registers new callback for each payment and asks user to pay to invoice address.
2. Client creates one invoice and registes one callback for whole application and asks user to provide some payment id in transaction details.

FIrst solution is more user friendly because it doesn require additional actions from user, but second is easier to implement programmatically. But I have some questions regarding both solutions:
 - If I implement first solution and client will register new callback for each payment how can I check that client can register more callbacks (not above the limit of 10 callbacks)? Also, client needs to remove callbacks after receiving the payment, how can I do that? How to check that callback for invoice is still alive (it's needed to remove secret token when callback was expired)?
 - If I use second solution, I need to know how to check that callback is alive, because application may register single callback, but it will be removed because it can expire.

What is preferable way to implement WTS callbacks?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#173` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
