### ISSUE TITLE
BTC not received after ZLD exchange

### ISSUE THREAD

**Issue by ypshenychka** [zold-io/wts.zold.io#174]
Zold were sold today. But actually no message in logs about exchange and no BTC arrived to wallet.

![image](https://user-images.githubusercontent.com/11703257/53878345-4ef95f00-4014-11e9-8b68-6507125f8db8.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka try to PULL. The transaction is still there? Should disappear and you can try to sell again.

**Comment by ypshenychka** [comment]
@yegor256 It disappeared and I've reselled - green confirmation message was shown. But this transaction is not even shown in my grid or in the log. And of course no BTC arrived.

![image](https://user-images.githubusercontent.com/11703257/53900161-91d32b00-4044-11e9-99db-7e460c108083.png)

**Comment by ypshenychka** [comment]
@yegor256 Same today. Looks like exchange doesn't work at all for me.

**Comment by yegor256** [comment]
@ypshenychka that's a separate problem now, but the first problem is solved. The current problem will be fixed here: #176

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#174` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
