### ISSUE TITLE
Can't sell Zold

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#177]
I'm trying to sell 100 ZLD but it's not possible because of error:
`With 100.00ZLD you are going over our limits: 270/3822/4484 vs 256/4096/8196 `
But these values are not correct: I didn't sell Zold for 2 days, so I don't understand why it thinks that I sold `270` today.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 you are hitting OUR limits. 270 ZLD were sold by ALL users today. That's why you can't sell. I will add more explanation now.

**Comment by yegor256** [comment]
@g4s8 see 71bd903

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#177` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
