### ISSUE TITLE
Graph values are not readable in some cases

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#179]
When graph is not changing for some time period, text values for points are overlapping each other, so it's not possible to read them. See screenshot attached:

![scrot-2019-03-10-13:12:44](https://user-images.githubusercontent.com/1524988/54083653-8f6c1c00-4337-11e9-8aba-a60fabdc76a7.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 fixed in ea6d9eb2e08deeee8832132db4d14fadda8964bf

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#179` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
