### ISSUE TITLE
show the banner when busy

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#18]
Let's show the banner on top of the page when we are busy. At the moment we only mark the `Log` menu item with red color. This is not enough. Let's also show the banner.

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.1`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#18` is not assigned, can't get performer
