### ISSUE TITLE
Use server-driven content negotiation instead of .json suffix

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#180]
It would be more conventional and expected to use service-driven [content negotiation](https://www.w3.org/Protocols/rfc2616/rfc2616-sec12.html) ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation) docs) via `Accept` header instead of `.json` suffix for API endpoints, such as `/rate`.
I think it will be more clear to use
 - `GET /rate` with `Accept: text/html` - for HTML page
 - `GET /rate` with `Accept: application/json` - for JSON

instead of
 - `GET /rate` - for HTML page
 - `GET /rate.json` - for JSON

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 but it's less convenient for end-users. With a suffix I can test both endpoints via my web browser. With Headers I have to use some HTTP client instead. That's why suffixes.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#180` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
