### ISSUE TITLE
ZLD sell amount is inconsistent

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#181]
I just sold 128 ZLD for 0.0346112 BTC using WTS. Telegram bot says that I exchanged 128 ZLD to BTC, but my transaction list contains only 117 ZLD (and 2.56 fee ZLD) what is 119.56, not 128 see screenshots:
![scrot-2019-03-11-12:41:41](https://user-images.githubusercontent.com/1524988/54114479-965c6280-43fb-11e9-875a-716cb4362b94.png)
![scrot-2019-03-11-12:40:11](https://user-images.githubusercontent.com/1524988/54114480-96f4f900-43fb-11e9-995a-018ac42cc606.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 this is super weird, thanks for noticing!

**Comment by yegor256** [comment]
@g4s8 fixed in 141660b67c6ae56ff269da0e0cd988caafab885f thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#181` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
