### ISSUE TITLE
Add status of job in output response

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/wts.zold.io#182]
The `/output` endpoint returns the log of a job but doesn't tell its status.

It will be nice to add a header determines if it's in progress, failed or succeeded.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ammaratef45 implemented in df6ab4e0f3c91e55ac67ad6be68b5a0a25fc5d08 thanks!

**Comment by 0crat** [comment]
This job is not in scope
