### ISSUE TITLE
Callback wasn't called

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#187]
0crat registered callback with id `15` for invoice `D9u07zaL@860261987eb8d2d3` and with regex `kyDFPizd` then I sent 1 ZLD to this invoice using WTS (added `kyDFPizd` to details), this payment was appeared on general ledger with id `43`, but callback `https://0crat.com/zcallback` was not called (I read http logs of 0crat to find this request).
![scrot-2019-03-13-12:21:53](https://user-images.githubusercontent.com/1524988/54267716-c7b76880-458a-11e9-9d0e-8140db36d293.png)
![scrot-2019-03-13-12:22:06](https://user-images.githubusercontent.com/1524988/54267722-cab25900-458a-11e9-90c8-e4ba72fa741d.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 let's try again, we will see logs in Telegram when callback is matched, and will be able to analyze what's going on

**Comment by g4s8** [comment]
@yegor256 done: callback id is 16

**Comment by yegor256** [comment]
@g4s8 the problem is that the callback URI you provide doesn't work. Let me make this problem visible in the dashboard...

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.1`

**Comment by yegor256** [comment]
@g4s8 should be better now

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#187` is not assigned, can't get performer

**Comment by g4s8** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
This job is not in scope
