### ISSUE TITLE
after zold sell for btc page not found

### ISSUE THREAD

**Issue by blackout314** [zold-io/wts.zold.io#189]
after sell zld for btc, redirect on not exist page

https://wts.zold.io/btc

```

Page Not Found

This page is not here. Most likely the link is broken or expired.
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@blackout314 fixed in d296c4c thanks

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#189` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
