### ISSUE TITLE
replace latch file with an atomic counter

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#19]
At the moment we have a "latch" file which is set and reset in `LatchOps`. The information it provides is not accurate, since I can call `pull` twice and the latch will be reset on the first success. It will be reset when the second call is still running. Let's reproduce this in a test and replace the latch with an atomic counter.

**Comment by 0crat** [comment]
Job [#19](https://github.com/zold-io/wts.zold.io/issues/19) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#19](https://github.com/zold-io/wts.zold.io/issues/19); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#19](https://github.com/zold-io/wts.zold.io/issues/19); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#19](https://github.com/zold-io/wts.zold.io/issues/19); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#19](https://github.com/zold-io/wts.zold.io/issues/19); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#19](https://github.com/zold-io/wts.zold.io/issues/19) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CB28FH2NR/2611632664); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@0crat wait - PR submitted, waiting for review

**Comment by 0crat** [comment]
> @0crat wait - PR submitted, waiting for review ([here](https://github.com/zold-io/wts.zold.io/issues/19#issuecomment-424293778))

@emilianodellacasa The impediment for [#19](https://github.com/zold-io/wts.zold.io/issues/19) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@emilianodellacasa no need to do this

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/wts.zold.io/issues/19#issuecomment-470504643))

@yegor256 Job `gh:zold-io/wts.zold.io#19` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#19` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#19](https://github.com/zold-io/wts.zold.io/issues/19) is now out of scope
