### ISSUE TITLE
Add endpoints for output size and average size of output

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/wts.zold.io#190]
For ammaratef45/zold-flutter-client#26, we need to add an endpoint to provide the output size of the job and the average size of outputs for previous jobs.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ammaratef45 fixed in b39da27c39616d972b00fc65291d0d63c392452a Try to use `/job.json`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#190` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
