### ISSUE TITLE
test coverage information is not correct

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#192]
Check this out: https://codecov.io/github/zold-io/wts.zold.io?branch=master The information is not correct. For example, `objects/item.rb` is definitely covered by `test_item.rb` but the coverage reports shows that only a few methods are covered.

**Comment by 0crat** [comment]
Job [#192](https://github.com/zold-io/wts.zold.io/issues/192) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
fixed

**Comment by 0crat** [comment]
The job [#192](https://github.com/zold-io/wts.zold.io/issues/192) is now out of scope
