### ISSUE TITLE
Potential threat of losing money

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/wts.zold.io#199]
I found that wts Telegram channel announce that my wallet won't get a bonus because it's not known to zerocracy every time I restart it.
If that means that zerocracy user can get a bonus every time he restarts the wallet this may be a way to attack and steal funds.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ammaratef45 yes, it's a known threat, thanks for reporting, let me fix it.

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.2`

**Comment by yegor256** [comment]
@ammaratef45 seems to be fixed, please check

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#199` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
