### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#200]
I'm getting error `@g4s8 doesn't work in Zerocracy, can't login via GitHub, use mobile phone instead`, but it's not correct.
it was fixed after page reload.
![scrot-2019-04-02-11:01:49](https://user-images.githubusercontent.com/1524988/55385990-1aa39080-5537-11e9-9e3f-fa31f34d3b8f.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#200` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
