### ISSUE TITLE
Incorrect amount on sell ZLD

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#205]
I just exchanged 124 ZLD to BTC, WTS claims that it sent me `0.0335296` BTC (in Telegram chat and on WTS page), but actually I've received `0.032904 BTC` (see transaction
`05d60d93497ecbcc0c2bab78f99913ceb5b5e11a84ff876b1a885f41567b699c`).
It seems that WTS takes a fee for exchange (should be 2%), but in such case it should show correct BTC values in Telegrm channel and page message.

![photo_2019-04-05_14-20-24](https://user-images.githubusercontent.com/1524988/55624283-1fbe4500-57ae-11e9-846d-40e8f5be85ad.jpg)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 coinbase took that money. We will move away from them soon and this fee won't be distracted anymore

**Comment by yegor256** [comment]
@g4s8  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by g4s8** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#205` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
