### ISSUE TITLE
Updating your wallet alert on pull

### ISSUE THREAD

**Issue by YoMe2** [zold-io/wts.zold.io#21]
STR:
1. Press Pull on https://wts.zold.io/home

http://prntscr.com/jv7clu

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@yome2[/z](https://www.0crat.com/u/yome2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@YoMe2 can you please try it again and confirm that the bug is still there?

**Comment by YoMe2** [comment]
http://prntscr.com/jvbtzt

'Page refresh in a minute' doesn't get rid of the alert

**Comment by yegor256** [comment]
@YoMe2 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#21` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
