### ISSUE TITLE
Couldn't create a wallet

### ISSUE THREAD

**Issue by agorlov** [zold-io/wts.zold.io#218]
Hello,

Problem with starting, creating wallet:
![image](https://user-images.githubusercontent.com/2485728/56845512-1adf4380-68cb-11e9-9967-007c719e1fdd.png)

Page where I getting startded with zold:
https://wts.zold.io/quick

My steps:
1. I opened https://wts.zold.io/quick, and clicked [Start] btn;
2. I entered phone number (starts with 7905205...);
3. I recieved sms and entered the code;
4. I rewrote the key and pressed continue (it took me 3 or 5 minutes, to get the paper)

Result:
I got an error. I expected some information about my new wallet.

The seccond and third attempts gives me the same error after the step 3.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@agorlov[/z](https://www.0crat.com/u/agorlov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@agorlov thanks for reporting, seems to be a bug on our side. While we are fixing it, you may try to use your account via wts.zold.io and there you can go to Buy/Sell and do the same operation as you were attempting to do at the `/quick` page.

**Comment by 0crat** [comment]
Thanks for your contribution, @agorlov[/z](https://www.0crat.com/u/agorlov)! If you would be a member of [the project](https://www.0crat.com/p/CB28FH2NR), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
Job [#218](https://github.com/zold-io/wts.zold.io/issues/218) is now in scope, role is `DEV`

**Comment by agorlov** [comment]
@yegor256 is it possible to get a bug-reward? I couldnt find the project on board page (https://www.0crat.com/board) I'm ready to accept it in the form of zold-coins (MWVX5Bhv@ca40737a4e7f8c57) :-)

**Comment by 0crat** [comment]
The job [#218](https://github.com/zold-io/wts.zold.io/issues/218) assigned to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), here is [why](https://www.0crat.com/footprint/CB28FH2NR/ccea9d7d-1684-4d80-8c81-3108072129eb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @oltdaniel[/z](https://www.0crat.com/u/oltdaniel) resigned from [#218](https://github.com/zold-io/wts.zold.io/issues/218), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by yegor256** [comment]
@agorlov it's fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#218` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#218](https://github.com/zold-io/wts.zold.io/issues/218) is now out of scope
