### ISSUE TITLE
bitcoin gateway not work

### ISSUE THREAD

**Issue by blackout314** [zold-io/wts.zold.io#220]
i sell ZLD for BTC 29/04/2019
```

#35 | -0.27 | 1d | 1b98e9e0ca2c58eb | Fee for exchange of 0.00361795 BTC at 36156cuHdUvT1UCA­hZQ3pctXjSeYmwJC­UE, rate is 0.0002704, fee is 0.02
#34 | -13.11 | 1d | e10ec8a0484a52e6 | ZLD exchange to 0.00361795 BTC at 36156cuHdUvT1UCA­hZQ3pctXjSeYmwJC­UE, rate is 0.0002704, fee is 0.02

```

btc never arrive

please refund me in ZLD, thx

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#220](https://github.com/zold-io/wts.zold.io/issues/220) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Comment by yegor256** [comment]
@blackout314 This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#220` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#220](https://github.com/zold-io/wts.zold.io/issues/220) is now out of scope

**Comment by blackout314** [comment]
@yegor256 please refund lost ZLD

**Comment by yegor256** [comment]
@blackout314 what is your wallet ID?

**Comment by blackout314** [comment]
@yegor256 bf1cbb2017040c3c

**Comment by yegor256** [comment]
@blackout314 sent
