### ISSUE TITLE
pull most recently used wallets on the background

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#221]
Let's keep track on most recently used wallets (in the database) and regularly (every 10 minutes) check whether they are present in the files and pull them. Let's keep an eye on 100 wallets only.

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.3`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#221` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
