### ISSUE TITLE
исчезли средства

### ISSUE THREAD

**Issue by tomjons** [zold-io/wts.zold.io#222]
после обновления кошелька исчезли 6 zld с аккаунта. Прошу разобраться и вернуть средства.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@tomjons[/z](https://www.0crat.com/u/tomjons) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
