### ISSUE TITLE
!Рестарт!

### ISSUE THREAD

**Issue by AlexisGarra** [zold-io/wts.zold.io#223]
я потерял все zld после рестарта, получения нового ключа  и после подтверждения кошелька.
меня даже не предупредило не одно всплывающее окно о том что я все потерял.
и хорошо , что сегодня еще zld не стоит 1000$ за 1zld. я потерял не 17500$  а всего лишь 17.5;$ 
Это не правильно

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@alexisgarra[/z](https://www.0crat.com/u/alexisgarra) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
