### ISSUE TITLE
duplicated incoming payments

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#225]
For some reason, we get duplicated BTC incoming payments.

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#225` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.2`
