### ISSUE TITLE
No staging environment

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#226]
WTS doesn't have staging environment, so it's not possible to write integration tests based on WTS API, because it requires production API keys and may affect production data.
An example where staging one might solve some issues is these tickets: https://github.com/zerocracy/farm/issues/2019 and https://github.com/zerocracy/farm/issues/1975 - for now, I just can't write a test using production 0crat API key to send funded callbacks, and it can affect WTS funding amounts.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 make sense, thanks, I will make something

**Comment by 0crat** [comment]
The job [#226](https://github.com/zold-io/wts.zold.io/issues/226) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB28FH2NR/0f7c880d-75cd-44be-a2b8-feb61615c0c2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 fixed in #231 You can play with it, just login via: https://wts.zold.io/sandbox

**Comment by 0crat** [comment]
The job [#226](https://github.com/zold-io/wts.zold.io/issues/226) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 thanks
