### ISSUE TITLE
X axis in rate graph (and others?) is wrong

### ISSUE THREAD

**Issue by vzurauskas** [zold-io/wts.zold.io#229]
BTC/ZLD exchange rate has been raised to 0.00028120 on May 10, however the [rate graph](https://wts.zold.io/rate) shows that it reached this number on May 1. Yesterday it showed a different day (don't remember, but I think it was April 30). Looks like the graph is shifted by ~10 days to the left.

Attaching a screenshot since the graph keeps changing every day.

![image](https://user-images.githubusercontent.com/18754033/57573936-b5499600-7438-11e9-932d-0bb1ffbf8094.png)

This may also be the case for other graphs.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vzurauskas[/z](https://www.0crat.com/u/vzurauskas) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@vzurauskas where would you expect it to show? The x-axis is discreet and has only a few points in time. The y-value is an average.

**Comment by vzurauskas** [comment]
@yegor256 

1) If there was no increase from from 04/20 to 05/01, I would expect the line from 04/20 to 05/01 not to show any increase and remain flat.
2) I would also expect the last point to be the current day. 
3) I did not expect it to be an average. If it's an average, it would be good to have it written somewhere close to the graphs that Y value is an average, and an average of what: previous n days, a period between previous n days and next n days, etc?

**Comment by yegor256** [comment]
@vzurauskas it's a simple graph drawing engine, see https://github.com/zold-io/wts.zold.io/blob/master/objects/graph.rb#L41-L80 If you want to fix it and know how to do it, please submit a pull request.

**Comment by vzurauskas** [comment]
@yegor256 Alright. Closing this.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#229` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
