### ISSUE TITLE
Couldn't log in with github account

### ISSUE THREAD

**Issue by paulodamaso** [zold-io/wts.zold.io#230]
I''m not being able o log in zold.wts.io with my github account. I'm receiving the following error:

`E103: "paulodamaso" doesn't work in Zerocracy, can't login via GitHub, use mobile phone (see KYC section in our Terms of Use) /2`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.5`

**Comment by yegor256** [comment]
@paulodamaso fixed, try again

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#230` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by paulodamaso** [comment]
@yegor256 Yes, it worked, thanks
