### ISSUE TITLE
transfer from hot to cold wallet automatically

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#233]
Let's transfer from hot wallets if they have more than X bitcoins.

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.8`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#233` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
