### ISSUE TITLE
ZLD to Upwork

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#236]
We have few potential Zeroracy users from Upwork, but they can accept only Upwork payments. So it would be good to have an option to convert ZLD to Upwork payments, then users will be able to receive payment via Upwork without customer actions.

// cc: @ypshenychka

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.34.0`

**Comment by yegor256** [comment]
@g4s8 it seems to be implemented, let's see how it works

**Comment by g4s8** [comment]
@yegor256 thanks
@ypshenychka now you can invite upwork users who want to withdraw via upwork

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#236` is not assigned, can't get performer
