### ISSUE TITLE
Unable to login via Github as non Zerocracy user. 

### ISSUE THREAD

**Issue by stepan-romankov** [zold-io/wts.zold.io#238]
I'm not part of Zerocracy group on Github but I created a wallet a long time ago and was login in  via Github. Since some time it's not possible to login via Github for non Zerocracy users. How it's possible to transfer zolds from this account to a newly created one (linked to phone number)?

P.S. I have Keygap but zold wallet was not associated with my private key.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@stepan-romankov[/z](https://www.0crat.com/u/stepan-romankov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@stepan-romankov you can login now.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#238` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
