### ISSUE TITLE
Layout issues on sell page

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#241]
After latest UI update some text hints for input fields were moved, and now it's not clear for which input text is shown. Looks like hint about address is shown for amount input and amount hint is just a text without input field.
![scrot-2019-05-18-11:09:42](https://user-images.githubusercontent.com/1524988/57966735-af831180-795e-11e9-9462-3f6b01ae49fb.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 what is the browser? I don't see it in Chrome.

**Comment by g4s8** [comment]
@yegor256 I'm using "Mozilla Firefox 66.0.5", just updated from previous version and still can see same issue. It was not reproduced before WTS UI updates.

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.4`

**Comment by yegor256** [comment]
@g4s8 how about now?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#241` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@yegor256 fixed, thanks

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#241` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
