### ISSUE TITLE
Unexpected error while processing request: Rack::Csrf::InvalidCsrfToken

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#243]
`Rack::Csrf::InvalidCsrfToken` when sending payments

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#243` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
