### ISSUE TITLE
No payment to bitcoin received

### ISSUE THREAD

**Issue by ypshenychka** [zold-io/wts.zold.io#247]
I've sold zld to btc 2 hours ago, and they're deducted from my wallet, but nothing received to btc account as well as no log record in wts.zold.io chat.
![image](https://user-images.githubusercontent.com/11703257/58337721-14eb6c80-7e4f-11e9-834d-c60e22b8147b.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ypshenychka what is your wallet ID?

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.5`

**Comment by ypshenychka** [comment]
@yegor256 zold wallet id is: d61f389eaf2b3327

**Comment by yegor256** [comment]
@ypshenychka I sent you 44 ZLD back. Hopefully this won't happen again. Sorry about this.

**Comment by yegor256** [comment]
@ypshenychka oops, it seems I sent you 44 twice. Can you please return back the second payment?

**Comment by ypshenychka** [comment]
@yegor256 I haven't received anything back yet. But let me know your wallet id, so that I know where to return extra payment.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#247` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by ypshenychka** [comment]
@yegor256 Is this your wallet ID? 3bd97355b8c58dc7

**Comment by yegor256** [comment]
@ypshenychka yes

**Comment by ypshenychka** [comment]
@yegor256 Done
![image](https://user-images.githubusercontent.com/11703257/58483704-6bb3b780-8169-11e9-9f4c-242345f4c351.png)
