### ISSUE TITLE
check nodes more accurately

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#248]
Let's fetch the real amount of them

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.7`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#248` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
