### ISSUE TITLE
Incorrect message that I don't work in zerocracy

### ISSUE THREAD

**Issue by Serranya** [zold-io/wts.zold.io#253]
When I am trying to login via github I get the following:
![grafik](https://user-images.githubusercontent.com/1206309/58568281-46d84680-8234-11e9-97d7-5dfa8e4009e3.png)

But I do work in zerocracy:
![grafik](https://user-images.githubusercontent.com/1206309/58568380-77b87b80-8234-11e9-8a87-eb09cdd2bc26.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@serranya[/z](https://www.0crat.com/u/serranya) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@Serranya just try again, this may be a temporary problem

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.12`

**Comment by Serranya** [comment]
@yegor256 Its still broken for me after the release.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#253` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
