### ISSUE TITLE
Zold WTS is failing to pay for 0crat issues solved

### ISSUE THREAD

**Issue by paulodamaso** [zold-io/wts.zold.io#254]
Zold WTS is having problems in getting me paid fopr issues resolved for 0crat:

> Zerocrat, [29.05.19 11:31]
> We tried to pay your debt of $5.83, but failed (Failed to pay: Failed to find wallet id; code=500 error=We are still busy with your wallet, check the Log); don't worry, we will retry very soon
> 
> Zerocrat, [29.05.19 11:36]
> We are very sorry, but we failed to pay you $5.83 for #398 (https://github.com/stryvers/life-lens-app/issues/398): "Failed to pay: Failed to pay via WTS: job=37468fd5-addc-4ad2-ab5d-39b28f08a966 error=We are sorry, but most probably the job is lost; try again..."; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 11:38]
> You got +10 point(s) in the job #398 (https://github.com/stryvers/life-lens-app/issues/398) in GFV03LPPY, your total is +7260 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28)
> 
> Zerocrat, [29.05.19 11:48]
> We tried to pay your debt of $5.83, but failed (Failed to pay: Zold payment failed; code=500 error=We are still busy with your wallet, check the Log); don't worry, we will retry very soon
> 
> Zerocrat, [29.05.19 11:57]
> We are very sorry, but we failed to pay you $20.42 for #425 (https://github.com/stryvers/life-lens-app/issues/425): "Debt already exists, adding payment of $20.42 for Payment for #425 (https://github.com/stryvers/life-lens-app/issues/425): Order was finished to debts"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 11:57]
> We are very sorry, but we failed to pay you $20.42 for #427 (https://github.com/stryvers/life-lens-app/issues/427): "Debt already exists, adding payment of $20.42 for Payment for #427 (https://github.com/stryvers/life-lens-app/issues/427): Order was finished to debts"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 11:58]
> You got +35 point(s) in the job #425 (https://github.com/stryvers/life-lens-app/issues/425) in GFV03LPPY, your total is +7330 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Order was finished
> 
> Zerocrat, [29.05.19 11:58]
> We are very sorry, but we failed to pay you $5.83 for #423 (https://github.com/stryvers/life-lens-app/issues/423): "Debt already exists, adding payment of $5.83 for Payment for #423 (https://github.com/stryvers/life-lens-app/issues/423): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28) to debts"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 11:58]
> You got +35 point(s) in the job #427 (https://github.com/stryvers/life-lens-app/issues/427) in GFV03LPPY, your total is +7340 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Order was finished
> 
> Zerocrat, [29.05.19 11:58]
> You got +10 point(s) in the job #423 (https://github.com/stryvers/life-lens-app/issues/423) in GFV03LPPY, your total is +7350 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28)
> 
> Zerocrat, [29.05.19 11:59]
> We are very sorry, but we failed to pay you $5.83 for #434 (https://github.com/stryvers/life-lens-app/issues/434): "Debt already exists, adding payment of $5.83 for Payment for #434 (https://github.com/stryvers/life-lens-app/issues/434): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28) to debts"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 11:59]
> You got +10 point(s) in the job #434 (https://github.com/stryvers/life-lens-app/issues/434) in GFV03LPPY, your total is +7350 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28)
> 
> Zerocrat, [29.05.19 11:59]
> We are very sorry, but we failed to pay you $5.83 for #435 (https://github.com/stryvers/life-lens-app/issues/435): "Debt already exists, adding payment of $5.83 for Payment for #435 (https://github.com/stryvers/life-lens-app/issues/435): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28) to debts"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 12:00]
> You got +10 point(s) in the job #435 (https://github.com/stryvers/life-lens-app/issues/435) in GFV03LPPY, your total is +7360 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28)
> 
> Zerocrat, [29.05.19 12:04]
> Join form was submitted by @nodir-sultan/z (https://www.0crat.com/u/nodir-sultan), you can check resumes page
> 
> Zerocrat, [29.05.19 12:49]
> We tried to pay your debt of $64.16, but failed (Failed to pay: Zold payment failed; code=500 error=We are still busy with your wallet, check the Log); don't worry, we will retry very soon
> 
> Zerocrat, [29.05.19 13:53]
> We tried to pay your debt of $64.16, but failed (Failed to pay: Zold payment failed; code=500 error=E219: We are still busy with your wallet, check the Log); don't worry, we will retry very soon
> 
> Zerocrat, [29.05.19 13:57]
> We are very sorry, but we failed to pay you $5.83 for #402 (https://github.com/stryvers/life-lens-app/issues/402): "Debt already exists, adding payment of $5.83 for Payment for #402 (https://github.com/stryvers/life-lens-app/issues/402): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28) to debts"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 13:58]
> You got +10 point(s) in the job #402 (https://github.com/stryvers/life-lens-app/issues/402) in GFV03LPPY, your total is +7370 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28)
> 
> Zerocrat, [29.05.19 14:07]
> You got -5 point(s) in the job #270 (https://github.com/stryvers/life-lens-app/issues/270) in GFV03LPPY, your total is +7360 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Manual assignment of issues is discouraged, see §19 (http://www.zerocracy.com/policy.html#19)
> 
> Zerocrat, [29.05.19 14:07]
> You got -5 point(s) in the job #239 (https://github.com/stryvers/life-lens-app/issues/239) in GFV03LPPY, your total is +7360 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Manual assignment of issues is discouraged, see §19 (http://www.zerocracy.com/policy.html#19)
> 
> Zerocrat, [29.05.19 14:09]
> You got -5 point(s) in the job #436 (https://github.com/stryvers/life-lens-app/issues/436) in GFV03LPPY, your total is +7355 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Manual assignment of issues is discouraged, see §19 (http://www.zerocracy.com/policy.html#19)
> 
> Zerocrat, [29.05.19 14:09]
> We are very sorry, but we failed to pay you $8.75 for #436 (https://github.com/stryvers/life-lens-app/issues/436): "Debt already exists, adding payment of $8.75 for Payment for #436 (https://github.com/stryvers/life-lens-app/issues/436): Bug was reported, see §29 (http://www.zerocracy.com/policy.html#29) to debts"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 14:09]
> You got +15 point(s) in the job #436 (https://github.com/stryvers/life-lens-app/issues/436) in GFV03LPPY, your total is +7370 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Bug was reported, see §29 (http://www.zerocracy.com/policy.html#29)
> 
> Zerocrat, [29.05.19 14:42]
> We tried to pay your debt of $78.74, but failed (Failed to pay: Zold payment failed; code=500 error=E189: GitHub user "paulodamaso" doesn't exist); don't worry, we will retry very soon
> 
> Zerocrat, [29.05.19 15:46]
> We tried to pay your debt of $78.74, but failed (Failed to pay: Zold payment failed; code=500 error=E219: We are still busy with your wallet, check the Log); don't worry, we will retry very soon
> 
> Zerocrat, [29.05.19 16:40]
> We tried to pay your debt of $78.74, but failed (Failed to pay: Zold payment failed; code=500 error=E219: We are still busy with your wallet, check the Log); don't worry, we will retry very soon
> 
> Zerocrat, [29.05.19 17:11]
> We are very sorry, but we failed to pay you $140.00 for none: "Debt already exists, adding payment of $140.00 for Payment for none: Release bonus for ARC §54 (http://www.zerocracy.com/policy.html#54) for tag 3.0.0 in repo stryvers/life-lens-app to debts"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 17:12]
> You got +240 point(s) in the job none in GFV03LPPY, your total is +7610 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Release bonus for ARC §54 (http://www.zerocracy.com/policy.html#54) for tag 3.0.0 in repo stryvers/life-lens-app
> 
> Zerocrat, [29.05.19 17:24]
> We are very sorry, but we failed to pay you $5.83 for #438 (https://github.com/stryvers/life-lens-app/issues/438): "Debt already exists, adding payment of $5.83 for Payment for #438 (https://github.com/stryvers/life-lens-app/issues/438): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28) to debts"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)
> 
> Zerocrat, [29.05.19 17:27]
> You got +10 point(s) in the job #438 (https://github.com/stryvers/life-lens-app/issues/438) in GFV03LPPY, your total is +7620 (https://www.0crat.com/u/paulodamaso/awards), see §18 (http://www.zerocracy.com/policy.html#18): Payment to ARC for a closed pull request, as in §28 (http://www.zerocracy.com/policy.html#28)
> 
> Zerocrat, [29.05.19 17:42]
> We tried to pay your debt of $224.57, but failed (Failed to pay: Zold payment failed; code=500 error=E219: We are still busy with your wallet, check the Log); don't worry, we will retry very soon

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.13`

**Comment by yegor256** [comment]
@paulodamaso should work now

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#254` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
