### ISSUE TITLE
manual transfer from cold to hot Bitcoin addresses

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#256]
Let's make it possible

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.15`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.17`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.18`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#256` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
