### ISSUE TITLE
Maximum concurrent requests for this endpoint reached

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#263]
Most probably due to this error an incoming BTC payment was missed:

```
Sibit::Error: Failed to retrieve /rawblock/0000000000000000001253a5f37d3763dbe928d21f7d72a708f05268c044179c (500): Maximum concurrent requests for this endpoint reached. Please try again shortly.Quota Exceeded (Servlet Limit)
  from sibit.rb:239:in `get_json'
  from objects/assets.rb:159:in `monitor'
  from syncem.rb:43:in `block in method_missing'
  from syncem.rb:41:in `synchronize'
  from syncem.rb:41:in `method_missing'
  from front/front_btc.rb:77:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start`
```

**Comment by AlexStich** [comment]
Good day.
Yesterday buy zold - about 6000 rub. equivalent, balance no change.
Wallet ID - c8595285413beec2

**Comment by AlexStich** [comment]
After updating wallet page balance doesn't change. 
Here screenshot of operation.
![Screenshot from 2019-06-17 09-57-40](https://user-images.githubusercontent.com/29394093/59584963-0e67b200-90e8-11e9-9ac5-42f2dc41a9b9.png)

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.25`

**Comment by 0crat** [comment]
The job [#263](https://github.com/zold-io/wts.zold.io/issues/263) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB28FH2NR/3069f4ca-9817-458d-8355-74162df4fcf3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@AlexStich I can't understand what happened, I will keep an eye on this bug. In the meantime, I've sent you 39 ZLD to your wallet, to compensate the error.

**Comment by yegor256** [comment]
```
NameError: undefined local variable or method `current' for main:Object
  from front/front_btc.rb:82:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.26`

**Comment by AlexStich** [comment]
@yegor256  Ok. Thanks. Balance is ok.

**Comment by 0crat** [comment]
Job [#263](https://github.com/zold-io/wts.zold.io/issues/263) is not in the agenda of @yegor256[/z](https://www.0crat.com/u/yegor256), can't set title
