### ISSUE TITLE
How to use the API to know taxes and wallet size?

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/wts.zold.io#264]
I want to implement ammaratef45/zold-flutter-client#104 but I need to get this info using the API
- taxes
- file size

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.27`

**Comment by yegor256** [comment]
@ammaratef45 see what was done in e61ea60. You should use `/head.json` to get all the details about the wallet.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#264` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by ammaratef45** [comment]
@yegor256 Thanks
