### ISSUE TITLE
White Paper in main page not found 404

### ISSUE THREAD

**Issue by rusnasonov** [zold-io/wts.zold.io#27]
https://wts.zold.io -> White Paper ( https://github.com/zold-io/papers/raw/master/wp.pdf ) -> Github 404

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@62c94ee0-47b0-4040-a917-bc85e86ebac6, thread: pool-110-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "catalog.xml" in "PMO" in 2min: e52044b7d4bb/7min/0/3/true/false by QuartzScheduler_Worker-8
```

[0.22.21](https://github.com/zerocracy/farm): Issue: zold-io/wts.zold.io#27, Action: `opened`

**Comment by yegor256** [comment]
@rusnasonov fixed in 4129f32 thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#27` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
