### ISSUE TITLE
Taxes part was deducted but no zold transferred to btc

### ISSUE THREAD

**Issue by ypshenychka** [zold-io/wts.zold.io#277]
I've sold zold to btc, but only transaction with taxes is shown and this taxes amount is deducted. No zold arrived to btc wallet.

<img width="857" alt="Screen Shot 2019-07-05 at 6 39 06 PM" src="https://user-images.githubusercontent.com/11703257/60735559-35313f80-9f54-11e9-8806-4dcdff68aabb.png">

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ypshenychka can you check what's in the `Log`? Click [here](https://wts.zold.io/log) to check.

**Comment by yegor256** [comment]
@ypshenychka also, it seems that no harm is done. Just do it again.

**Comment by ypshenychka** [comment]
@yegor256 right now I see this and reloading page in few minutes didn't work. 
<img width="864" alt="Screen Shot 2019-07-05 at 11 22 16 PM" src="https://user-images.githubusercontent.com/11703257/60745707-ccf65400-9f7b-11e9-8e19-f9c701df406c.png">

**Comment by ypshenychka** [comment]
@yegor256 Just tried again - and same thing. Taxes are deducted only. Will paste log entry below.
<img width="800" alt="Screen Shot 2019-07-05 at 11 33 38 PM" src="https://user-images.githubusercontent.com/11703257/60746097-6bcf8000-9f7d-11e9-8f9e-8f1cea8b0a29.png">

**Comment by ypshenychka** [comment]
@yegor256 Here's an error from logs.
1.02ZLD of taxes paid from d61f389eaf2b3327 to 90d1c9dc00001222 (payment no.1, txn #60/689), -0.00ZLD left to pay
The wallet is in good standing, all taxes paid
ERROR: RuntimeError: There is not enough funds in d61f389eaf2b3327 to send 24.50ZLD, only 24.33ZLD left; the difference is 741535353 zents
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/commands/pay.rb:141:in `pay'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/commands/pay.rb:107:in `block in run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/sync_wallets.rb:47:in `block (2 levels) in acq'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/sync_wallets.rb:46:in `block in acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/cached_wallets.rb:51:in `block in acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/wallets.rb:71:in `acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/cached_wallets.rb:49:in `acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/sync_wallets.rb:45:in `acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/commands/pay.rb:106:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.30/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/objects/ops.rb:171:in `block in pay'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tempfile.rb:295:in `open'
	/app/objects/ops.rb:168:in `pay'
	/app/front/front_btc.rb:369:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:43:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/versioned_job.rb:40:in `call'
	/app/objects/tracked_job.rb:34:in `call'
	/app/objects/safe_job.rb:36:in `call'
	/app/objects/exclusive_job.rb:35:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/exclusive_job.rb:34:in `call'
	/app/objects/async_job.rb:44:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:43:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

**Comment by ypshenychka** [comment]
@yegor256 Please advise. Taxes are deducted again, but no money transferred.

**Comment by yegor256** [comment]
@ypshenychka you are trying to send more ZLDs than you have. You have 24.50 and you are sending all of them out. But before sending them the taxes are paid (1.02 ZLD) and your wallet has not enough to send 24.50. And it crashes. Let me see what we can do to make this situation more obvious. In the meantime, try to click [/pull](https://wts.zold.io/pull) and send a smaller amount out.

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.39`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#277` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by ypshenychka** [comment]
@yegor256 Yep, it worked with smaller amount. However I would expect it to throw an error right away without deducting any taxes. I hope that's how you've fixed it :) Thanks.
