### ISSUE TITLE
show wallet owners

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#281]
In the `/payables` page

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.41`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.41`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#281` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
