### ISSUE TITLE
skip 127.0.0.1 in the list of remotes

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#285]

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.43`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.44`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#285` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
