### ISSUE TITLE
Hosting bonuses is not paid since 14.07.2019

### ISSUE THREAD

**Issue by aivinog1** [zold-io/wts.zold.io#288]
I see that since this message: https://t.me/zold_wts/6248 in the zold's channel: https://t.me/zold_wts there weren't messages about a hosting bonus. As described here: https://blog.zold.io/2018/08/14/hosting-bonuses.html I create this ticket.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 we just don't enough funds for them.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#288` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
