### ISSUE TITLE
NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by yaralink** [zold-io/wts.zold.io#29]
![screenshot 2018-06-22 at 3 32 04 pm](https://user-images.githubusercontent.com/29410203/41771192-0526eaa0-7634-11e8-8a00-622e6fe8ac9f.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@yaralink[/z](https://www.0crat.com/u/yaralink) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@yaralink fixed, thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#29` is not assigned, can't get performer
