### ISSUE TITLE
error in telegram auto-answer

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#291]
let's fix

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.46`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.46`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#291` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
