### ISSUE TITLE
Can't log in via Github, even though I work in Zerocracy

### ISSUE THREAD

**Issue by carlosmiranda** [zold-io/wts.zold.io#292]
I am seeing this frequently since yesterday. I thought it was a transient issue, but I saw it again today:

![image](https://user-images.githubusercontent.com/1917892/62339627-36cc3400-b50f-11e9-923d-d9fcfbf3d720.png)

Same error as #200?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.47`

**Comment by yegor256** [comment]
@carlosmiranda should be better now

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#292` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
