### ISSUE TITLE
did not receive BTC. job ID is c2749b4e-8a2d-43­8c-b46f-fa009bc7­cced

### ISSUE THREAD

**Issue by mmbug** [zold-io/wts.zold.io#295]
my Zold wallet is bd6a06be645eb711

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@mmbug[/z](https://www.0crat.com/u/mmbug) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by mmbug** [comment]
my Zold wallet is bd6a06be645eb711

**Comment by yegor256** [comment]
@mmbug refunded

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#295` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
