### ISSUE TITLE
WTS - Sending money to Paypal failed

### ISSUE THREAD

**Issue by bkuzmic** [zold-io/wts.zold.io#302]
I've exchanged ZLD to Paypal and WTS took my ZLDs but Paypal canceled the transaction saying payment from Zerocracy, Inc. was not processed successfully at the sender's side.

My wallet is: `8f3308ef3bf2fd7c`. Transactions are 6 and 7 and job id is: `1691cc49-ba2c-49­b0-b961-3cd8271a­ee70`
![wts](https://user-images.githubusercontent.com/178479/66573471-03430100-eb73-11e9-8592-c523faaac7bf.jpg)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by bkuzmic** [comment]
@yegor256 Can you please take a look where my 50 zolds went missing?

**Comment by bkuzmic** [comment]
@yegor256 Can somebody else take a look at this issue? It is really bad for the zolds to disappear like this.

**Comment by bkuzmic** [comment]
More details:
Transaction ID on Paypal side: 0LJ53394343100635. Status: Canceled.

**Comment by yegor256** [comment]
@bkuzmic I sent you 52 ZLD to your wallet 8f3308ef3bf2fd7c. Sorry about this, thanks for your patience.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#302` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
