### ISSUE TITLE
Taxes part was deducted but no zold transferred to btc

### ISSUE THREAD

**Issue by ypshenychka** [zold-io/wts.zold.io#307]
Same issue as in #277.

I've sold zold to btc, but only transaction with taxes is shown and this taxes amount is deducted. No zold arrived to btc wallet.
![image](https://user-images.githubusercontent.com/11703257/69651268-7ef00300-1078-11ea-968b-3f34b15b1be6.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.60`

**Comment by yegor256** [comment]
@ypshenychka just click PULL, the wallet data will be fixed

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#307` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
