### ISSUE TITLE
index TABLE is not mobile friendly

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#31]
Let's turn it into a collection of `<P>` when the screen is too narrow.

**Comment by 0crat** [comment]
Job [#31](https://github.com/zold-io/wts.zold.io/issues/31) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#31](https://github.com/zold-io/wts.zold.io/issues/31); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#31](https://github.com/zold-io/wts.zold.io/issues/31); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#31](https://github.com/zold-io/wts.zold.io/issues/31) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CB28FH2NR/8ce4121f-a291-4a0b-b9f3-2ce1728e087b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
fixed with Tacit 1.4.2

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.3`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#31` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#31](https://github.com/zold-io/wts.zold.io/issues/31) is now out of scope
