### ISSUE TITLE
WTS took ZLD but didn't send BTC

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#311]
I've tried to exchange 225 ZLD to BTC from [3be3416c805e4371](http://www.zold.io/ledger.html?wallet=3be3416c805e4371) wallet, transactions `122` and `123`
![scrot-2019-12-11-17:29:19](https://user-images.githubusercontent.com/1524988/70630169-2efa6a00-1c3c-11ea-8bca-1f53a60e7f30.png)

WTS took ZLD but didn't send BTC to the wallet `bc1q33rvhe95s5ac5teulyq4mm3gy7ag6vgxswd8um`. 

It's quite popular bug in WTS where it takes ZLD but didn't send exchanged value (it just happened third time with me), I think WTS should not take ZLD from wallets until it successfully send exchanged BTC or Paypal transaction.

See #294, #283, #309

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 as you see [here](http://www.zold.io/ledger.html?wallet=3be3416c805e4371) your wallet is not changed. Do the PULL in Wts and your wallet will get back to its state.

**Comment by yegor256** [comment]
@g4s8 this happens when you are trying to convert everything you have in your wallet. Taxes get deducted first and the transaction fails. Try to leave some space for taxes.

**Comment by g4s8** [comment]
@yegor256 thanks, it's working after pull

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#311` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
