### ISSUE TITLE
btc.com api

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#312]

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.55`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#312` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.56`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.57`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.58`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.59`
