### ISSUE TITLE
WTS can't see my Github account

### ISSUE THREAD

**Issue by vzurauskas** [zold-io/wts.zold.io#316]
Zerocrat just told me this:

```
We are very sorry, but we failed to pay you $x.xx for #xxx: "Failed to pay: Zold payment failed; code=500 error=E189: GitHub user "vzurauskas" doesn't exist";
```

"vzurauskas" does exist, here it is: https://github.com/vzurauskas

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vzurauskas[/z](https://www.0crat.com/u/vzurauskas) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by vzurauskas** [comment]
@yegor256 I still can't receive any Zold payments from Zerocracy.

**Comment by yegor256** [comment]
@rultor release, tag is `0.36.2`

**Comment by yegor256** [comment]
@vzurauskas let me try to fix this...

**Comment by yegor256** [comment]
@rultor release, tag is `0.36.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.36.2`

**Comment by vzurauskas** [comment]
@yegor256 Seems to be working now, thanks.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#316` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
