### ISSUE TITLE
Failed to pay: Zold payment failed; code=500 error=E189: GitHub user "iakunin" doesn't exist

### ISSUE THREAD

**Issue by iakunin** [zold-io/wts.zold.io#319]
> We tried to pay your debt of $34.80, but failed (Failed to pay: Zold payment failed; code=500 error=E189: GitHub user "iakunin" doesn't exist); don't worry, we will retry very soon

I received this message from Zecocrat telegram-bot multiple times:
1. 2020-01-23T23:46
1. 2020-01-24T00:47
1. 2020-01-24T01:53
1. 2020-01-24T02:49
1. 2020-01-24T10:14
1. 2020-01-24T10:53
1. 2020-01-24T11:43
1. 2020-01-24T12:44
1. 2020-01-24T13:48
1. 2020-01-24T15:56
1. 2020-01-25T13:14
1. 2020-01-26T12:50

At the same time I can log in into https://wts.zold.io using my github account.

@g4s8 said [here](https://github.com/zerocracy/farm/issues/2222#issuecomment-578480016) that:
>  this messages comes from WTS API, 0crat just shows this error response from WTS.

Therefore I opened this issue here.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@iakunin we are working on this issue.

**Comment by yegor256** [comment]
@rultor release, tag is `0.36.3`

**Comment by yegor256** [comment]
@iakunin this is fixed

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#319` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by iakunin** [comment]
@yegor256 many thanks. Let's wait for next Zerocrat attempt to repay the debt. I'll get you know about the result.

**Comment by iakunin** [comment]
@yegor256 my debt has been repaid. Thank you so much!
