### ISSUE TITLE
Anonymize the Search Wallet page

### ISSUE THREAD

**Issue by amihaiemil** [zold-io/wts.zold.io#322]
At the moment I think anyone can search a wallet's transasctions if they know its id. For instance this is my wallet: http://www.zold.io/ledger.html?wallet=38dfc77fede6b721

I personally don't like the idea of anyone knowing all my transactions.
I think this page should be anonymized (no username or email displayed). I would guess it should also be anonymized in order to comply with GDPR...

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@amihaiemil the best we can do is disable payment comments in Zerocrat. You can also omit payment comments. This will anonymize your data. Aside from that we can't do anything else. Just like in Blockchain, this data is public and open.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#322` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
