### ISSUE TITLE
Taxes should be payable via wts UI

### ISSUE THREAD

**Issue by amihaiemil** [zold-io/wts.zold.io#324]
According to [this post](https://blog.zold.io/2019/01/15/taxes-explained.html) we have to install the ``zold`` CLI tool in order to pay our taxes.

Wouldn't it be easier to have a "Pay taxes" button on wts.zold.io?

You also have to take into account that ZLD may be used by non-programmers who have never installed or worked with the CLI in their life.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@amihaiemil WTS automatically pays your taxes when it's time to do so. You don't need to worry about it, it happens behind the scene.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#324` is not assigned, can't get performer
