### ISSUE TITLE
Login doesn't work well

### ISSUE THREAD

**Issue by amihaiemil** [zold-io/wts.zold.io#325]
I log in via Github (I am a ZC member) and then, almost every time I refresh a page, I get logged out and have to login again. 

Having the experience of literally any webapp on the Internet, login should persist in a session, until I log out.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@amihaiemil are you sure? I've never seen this. Does it still happen now?

**Comment by amihaiemil** [comment]
@yegor256 well, I kept testing yesterday and today and I didn't see the problem anymore. But it definitely was present. Maybe it was fixed in the meantime...

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#325` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
