### ISSUE TITLE
Comission From ZC Workers Is Not Fair

### ISSUE THREAD

**Issue by amihaiemil** [zold-io/wts.zold.io#326]
Taking a 2% comission from Zerocracy workers is not fair because they do not have other options of payment. So we are forced to be paid in ZLD, and ZC in turn takes a comission (not to mention, 2% is a huge comision).

Comission (if any) should apply only to people who use ZLD by choice. ZC workers do not have a choice.

**Comment by yegor256** [comment]
@amihaiemil just increase your ZC hourly rate and that's it.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#326` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
