### ISSUE TITLE
Being a Zerocracy team member, I cannot login with GitHub

### ISSUE THREAD

**Issue by HDouss** [zold-io/wts.zold.io#331]
I joined Zerocracy team few days ago and starting gaining reputation, but I still cannot login with my GitHub id in zold.io into web wallet. I suspect a case sensitiveness problem. This is the message I get: "E103: "HDouss" doesn't work in Zerocracy, can't login via GitHub, use mobile phone (see KYC section in our Terms of Use); this may also be a temporary network problem, which you may solve by just trying again in a few minutes"

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@hdouss[/z](https://www.0crat.com/u/hdouss) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@HDouss this definitely is a case-sensitivity issue: https://www.0crat.com/known/HDouss (doesn't work), this works: https://www.0crat.com/known/hdouss Let me fix now.

**Comment by yegor256** [comment]
@rultor release, tag is `0.36.5`

**Comment by yegor256** [comment]
@HDouss should be fixed, please try

**Comment by HDouss** [comment]
@yegor256 works like a charm. Thanks!

**Comment by HDouss** [comment]
@yegor256 It is not that big deal, but I expected to have 0.256 in my wallet as it is stated here : "Once you sign-up, you will receive a bonus of 0.256 ZLD to your wallet"

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#331` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
