### ISSUE TITLE
fetch Bitcoin blocks from all possible sources

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#339]

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#339` is not assigned, can't get performer
