### ISSUE TITLE
Your wallet doesn't exist on our server yet.

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#34]
I created new wallet and receive 8 ZLD for signup, it was displayed for some time, but after pull I'm getting this message:
> Your wallet doesn't exist on our server yet.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#34](https://github.com/zold-io/wts.zold.io/issues/34) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB28FH2NR/1810551059); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#34` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 will be fully fixed after this one is implemented: https://github.com/zold-io/zold/issues/315

**Comment by botanicus** [comment]
Upon sign-up, I'm getting wallet ID, with the same message `Your wallet doesn't exist on our server yet. Please, pull it from the network!` And clicking the pull link doesn't fix it.

I believe this is the same issue.

**Comment by victornoel** [comment]
@yegor256 for the record, I'm having the same problem, the logs says the wallet is not found in any of the nodes.

Also, 0crat has been sending me zold (I am supposing on that wallet, even though this is nowhere explicit), does this mean it will be lost?

**Comment by yegor256** [comment]
@victornoel it the wallet is not found, it's lost. Just click "Restart" and start from scratch. We had issues recently, that's why.

**Comment by victornoel** [comment]
@yegor256 ok, and how come 0crat has been able to pay to it then? Is that a problem with 0crat?

**Comment by yegor256** [comment]
@0crat doesn't get a confirmation back from WTS. It just "drops" a payment to WTS and expects it to do the payment. It's a slow operation, as you understand. When exactly (and whether) the network will confirm the payment -- 0crat doesn't know.

**Comment by 0crat** [comment]
> @0crat doesn't get a confirmation back from WTS. It just "drops" a payment to WTS and expects it ... ([here](https://github.com/zold-io/wts.zold.io/issues/34#issuecomment-406204455))

@yegor256 Can't understand "doesn't", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by tt1403936** [comment]
The problem still exists in wts. After payment from wts to some other wallet, wts wallet actually pushed to network and could be pulled back after wts lost it.

**Comment by yegor256** [comment]
@g4s8 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job [#34](https://github.com/zold-io/wts.zold.io/issues/34) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
