### ISSUE TITLE
new monitoring of assets

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#340]

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.12`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#340` is not assigned, can't get performer
