### ISSUE TITLE
Unable to login with github or to list my wallet transactions

### ISSUE THREAD

**Issue by HDouss** [zold-io/wts.zold.io#344]
After #331 resolution, I was able to login with GitHub. It is not the case today and I have the same message "E103: "HDouss" doesn't work in Zerocracy, can't login via GitHub, use mobile phone (see KYC section in our Terms of Use); this may also be a temporary network problem, which you may solve by just trying again in a few minutes".
Besides, I could not find any transaction in my wallet when I visit: http://www.zold.io/ledger.html?wallet=47e7dc1cd0b735fc (47e7dc1cd0b735fc being my wallet id).
In my wallet I received some payments from working in zerocracy projects, and I did not sell or spend any zold ever (so only crediting transactions).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.13`

**Comment by yegor256** [comment]
@HDouss please, try again now.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#344` is not assigned, can't get performer

**Comment by HDouss** [comment]
@yegor256 I managed to login with github since yersterday, but I always have the message "Your wallet doesn't exist on our server yet." Is my money lost?
