### ISSUE TITLE
No spaces in payment messages

### ISSUE THREAD

**Issue by fanifieiev** [zold-io/wts.zold.io#345]
![image](https://user-images.githubusercontent.com/3167940/78585769-69e66600-7808-11ea-9d34-ef955ab943ea.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.38.1`

**Comment by yegor256** [comment]
@fanifieiev fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#345` is not assigned, can't get performer

**Comment by fanifieiev** [comment]
> @fanifieiev fixed, thanks!

@yegor256 Thanks too
