### ISSUE TITLE
E146: You don't have enough to send

### ISSUE THREAD

**Issue by alexstich** [zold-io/wts.zold.io#356]
Hi.
I can't sell zolds. I want sell all zolds i have (i write correct amount), but error appears:
E146: You don't have enough to send

My wallet is - c8595285413beec2

![Screenshot from 2020-05-24 15-59-45](https://user-images.githubusercontent.com/29394093/82754811-2b1c6780-9dd8-11ea-85b6-15daa87925f5.png)
![Screenshot from 2020-05-24 16-00-05](https://user-images.githubusercontent.com/29394093/82754812-2eafee80-9dd8-11ea-8868-639d7ac1446e.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@alexstich just try a bit smaller amount, should work
