### ISSUE TITLE
WTS may send invalid rates data

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#359]
WTS `/rates.json` response contains `valid` flag, it means that the response can be invalid. I think it's not correct to send invalid rates data to a user. I'd suggest removing this flag and return HTTP error in case if WTS is not able to fetch rates data internally (e.g. 500 error would be ok).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
see also #358

**Comment by yegor256** [comment]
@g4s8 in this case unit tests will break :) OK, I will think about a solution now

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.6`

**Comment by yegor256** [comment]
@g4s8 I made it equal to zero. In this case, no payment operations will succeed, which will protect us from money losses. Just pay attention to the `valid` flag and you will be safe on Zerocrat side.

**Comment by g4s8** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#359` is not assigned, can't get performer
