### ISSUE TITLE
/do-pay API doesn't url-decode params

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#36]
According to `/do-pay` API documentation form data should be urlencoded:
```
Content-Type: application/x-www-form-urlencoded
```
but looks like wts.zold.io doesn't decode it back before creating new transaction:
> ERROR: RuntimeError: Wrong details "Payment+to+%60ARC%60+for+a+closed+pull+request%2C+as+in+%5B%C2%A728%5D%28http%3A%2F%2Fwww.zerocracy.com%2Fpolicy.html%2328%29" ([a-zA-Z0-9 @\!\?\*_\-\.:,']+)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#36](https://github.com/zold-io/wts.zold.io/issues/36) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#36](https://github.com/zold-io/wts.zold.io/issues/36); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by 0crat** [comment]
> @0crat assign @botanicus ([here](https://github.com/zold-io/wts.zold.io/issues/36#issuecomment-403004267))

@yegor256 The job [#36](https://github.com/zold-io/wts.zold.io/issues/36) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CB28FH2NR/1871112627); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by botanicus** [comment]
@g4s8 how do I reproduce? I need either stack trace or a curl command to reproduce.

**Comment by g4s8** [comment]
@botanicus you need to obtain API key first on wts.zold.io, then you can access it with curl, e.g. this request will send `0.01 ZLD` to `yegor256`:
```sh
export WTS_KEY="your-key"
curl https://wts.zold.io/do-pay -X POST -d "bnf=yegor256&amount=0.01&details=API+test" -H "X-Zold-Wts: ${WTS_KEY}" -v
```

**Comment by botanicus** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/wts.zold.io/issues/36#issuecomment-403228860))

@botanicus The impediment for [#36](https://github.com/zold-io/wts.zold.io/issues/36) was registered successfully by @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by botanicus** [comment]
I'm putting it on hold since I have no ZLD due to the issue #34.

**Comment by g4s8** [comment]
@botanicus I suppose it can't

**Comment by yegor256** [comment]
@botanicus what's up with this? To get some ZLD just hit "Restart" and you will get 8ZLD as a signup bonus.

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/wts.zold.io/issues/36#issuecomment-410333699))

@yegor256 The job [#36](https://github.com/zold-io/wts.zold.io/issues/36) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CB28FH2NR/2151844129); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@0crat wait - for the PR to be accepted

**Comment by 0crat** [comment]
> @0crat wait - for the PR to be accepted ([here](https://github.com/zold-io/wts.zold.io/issues/36#issuecomment-411660551))

@emilianodellacasa The impediment for [#36](https://github.com/zold-io/wts.zold.io/issues/36) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@g4s8 I tried using _curl_ of your example but the payment has been successful, Sinatra is correctly parsing the params;

The problem with your original details _Payment+to+%60ARC%60+for+a+closed+pull+request%2C+as+in+%5B%C2%A728%5D%28http%3A%2F%2Fwww.zerocracy.com%2Fpolicy.html%2328%29_ is that ":" character is not accepted by Zold

**Comment by emilianodellacasa** [comment]
@yegor256 I think you can close this issue

**Comment by g4s8** [comment]
@emilianodellacasa got it, thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#36](https://github.com/zold-io/wts.zold.io/issues/36) is now out of scope

**Comment by ypshenychka** [comment]
@g4s8 I assume I can evaluate this ticket as acceptable, since some investigation work was done, right?

**Comment by ypshenychka** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@ypshenychka I think you can

**Comment by ypshenychka** [comment]
@g4s8 thank you

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
