### ISSUE TITLE
Exchanged ZLD to BTC, but no BTC has arrived

### ISSUE THREAD

**Issue by golyalpha** [zold-io/wts.zold.io#362]
Yesterday evening (about 8 hours ago now), I've tried to exchange some Zold for BTC, and while the Zold got sent off from my wallet, no BTC has arrived yet.

ZLD Wallet ID: 11d60619d8cbe9a3

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d3b7a9e0-0de0-4aa0-81d7-91e206bb2a2c, thread: pool-22-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to zold-io/wts.zold.io#362: @yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue
```

[0.53.15](https://github.com/zerocracy/farm): Issue: zold-io/wts.zold.io#362, Action: `opened`

**Comment by yegor256** [comment]
@golyalpha I refunded the payment. something went wrong on the server side.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#362` is not assigned, can't get performer

**Comment by golyalpha** [comment]
@yegor256 Should I retry to exchange?
