### ISSUE TITLE
/do-pay API ignores failure

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#37]
If `/do-pay` api fails with internal error (e.g. like in this bug: #36), it doesn't return error code, but return 303 (as expected), so client can't be sure that transaction was sent.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 this is by design. We send payments in a background thread and this may take some time. We can't return anything to your PUT request.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#37` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
