### ISSUE TITLE
Transfer from ZLD to BTC not received

### ISSUE THREAD

**Issue by victornoel** [zold-io/wts.zold.io#372]
I converted ZLD to BTC from my WTS account (at 2020-08-24T21:17Z), the transaction appears in my wallet (@victornoel) but I never received them.

Can you please fix it?

**Comment by yegor256** [comment]
@victornoel do you have more details? Your wallet ID at least.

**Comment by victornoel** [comment]
@yegor256 I thought you could find it from my zerocracy username. I didn't share it on purpose, but I guess it's useless since all WTS logs are public. Here it is: http://www.zold.io/ledger.html?wallet=90db378d8ce7bf5f, it's the last transaction.

**Comment by yegor256** [comment]
@victornoel here is the problem: https://wts.zold.io/job?id=b883583f-67a0-4e00-9dfa-aebba83c4d1f

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.17`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#372` is not assigned, can't get performer
