### ISSUE TITLE
Lock to the last stable major Ruby version

### ISSUE THREAD

**Issue by botanicus** [zold-io/wts.zold.io#38]
We discussed similar issue in https://github.com/zold-io/zold/issues/306. Here, however, the situation is different. Where zold is used for the public and therefore should run on wide set of environments, this app really is mostly for us.

Therefore, I propose, we lock against the latest stable major Ruby version, which as of now is Ruby 2.5[1].

I believe it will save us a lot of grief when in the future, esp. if we use the `frozen_string_literal` comments and hence will mark all strings as immutable as they will be in Ruby 3. It’s a big advantage starting with it from the beginning, it’s a real pain fixing it in the future (trust me on that, I’m trying to fix my projects now).

Besides, this way we get all the new Ruby features and they are quite a few pretty useful ones.

**Next steps:**
- Change the Gemfile.
- Document supported version in the README.
- Change Travis CI and Appveyor configuration to Run against Ruby 2.5.

___

[1] Alternative we can follow the route of zold, supporting Ruby 2.3+, but I say the scenario is different and using the latest major version is desirable.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#38](https://github.com/zold-io/wts.zold.io/issues/38) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
The job [#38](https://github.com/zold-io/wts.zold.io/issues/38) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CB28FH2NR/5ddf511d-a3d4-4e1b-848b-31739a9482c9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@botanicus 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/wts.zold.io/issues/38#issuecomment-470503667))

@yegor256 Job `gh:zold-io/wts.zold.io#38` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#38` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#38](https://github.com/zold-io/wts.zold.io/issues/38) is now out of scope
