### ISSUE TITLE
more logs on reconcile

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#390]

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.29`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.29`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.29`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.30`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#390` is not assigned, can't get performer
