### ISSUE TITLE
My withdraw to bitcoin didn't get send to my bitcoin wallet

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/wts.zold.io#395]
I sent zold to btc from my wallet and this transaction happened
```
#18 | -49.98 | 1d | e10ec8a0484a52e6 | ZLD␣exchange␣to␣0.0146268␣BTC␣at␣34nTGQ8KokoHDbDrJkoiJaLWM9a6WF2HSb,␣rate␣is␣0.0002868,␣fee␣is␣0.02,␣job␣ID␣is␣7b61e4cb-f045-40dc-bb40-0f438befe0cf
-- | -- | -- | -- | --
```

My Bitcoin never arrived though

That is my wallet ID: `25a9cac1715a3726`

**Comment by yegor256** [comment]
@ammaratef45 we refunded you 51ZLD to your wallet e10ec8a0484a52e6 Try again after the release, please.

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.36`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.36`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#395` is not assigned, can't get performer
