### ISSUE TITLE
Progress indicator on pull

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#40]
It's not very comfortable to manually refresh page when pulling from network, I think it would be better to show progress indicator when pulling and automatically refresh page on complete.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#40](https://github.com/zold-io/wts.zold.io/issues/40) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#40](https://github.com/zold-io/wts.zold.io/issues/40) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CB28FH2NR/eddc13a7-8064-4739-9457-12c038219091); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amorenew** [comment]
@yegor256 what about mobile apps how could we track "complete status"?

**Comment by yegor256** [comment]
@g4s8 it's not possible to do that, we don't know how long it may take. The best you can do is to refresh the `/log` page. @amorenew the same for mobile apps -- check the `/job` page.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#40` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#40](https://github.com/zold-io/wts.zold.io/issues/40) is now out of scope
