### ISSUE TITLE
Not enough BTC funds but my zold wallet was debited

### ISSUE THREAD

**Issue by HDouss** [zold-io/wts.zold.io#400]
Hello,
I tried to sell some of my zold and get BTC with 2 transactions on 17th April. In wts page, I can read "We can send up to 0.0154 BTC now". I did not receive my BTC yet. job ids are 77185c45-848f-472f-b0a1-0b6d1603020b and 4053d155-07ed-4aaf-878d-be8652c30ef6
In the Log, for the 2nd transaction, I see : "ERROR: Sibit::Error: Not enough funds to send 1,491,086s/$813.76, only 0s/$0.00 left"
My wallet was debited (even the transaction fees was debited.)

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.40`

**Comment by yegor256** [comment]
@HDouss refunded the missing payment
