### ISSUE TITLE
--ignore-score-weakness when paying taxes

### ISSUE THREAD

**Issue by davvd** [zold-io/wts.zold.io#415]

**Comment by davvd** [comment]
@rultor release, tag is `0.41.1`

**Comment by davvd** [comment]
@rultor release, tag = `0.41.2`

**Comment by davvd** [comment]
@rultor release, tag = `0.41.3`

**Comment by davvd** [comment]
@rultor release, tag = `0.41.4`

**Comment by davvd** [comment]
@rultor release, tag = `0.41.4`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#415` is not assigned, can't get performer
