### ISSUE TITLE
Use JSON instead of text/plain

### ISSUE THREAD

**Issue by botanicus** [zold-io/wts.zold.io#42]
JSON is the standard for web app APIs. If we plan to allow other users to use the `wts.zold.io` API, we should expose it in the (most) standard format.

Even if we don’t, there are other good reasons to use JSON:

As of now, `GET /version` returns `VERSION` as a string. That’s perfectly reasonable, but say that as we exposed `Zold::PROTOCOL`, we might want to expose that in here as well (or we might _not_, but I’ll just use it as an example).

With `text/plain` there are realistically 2 ways of implementing this:
1. `GET /version` could return `version: a.b.c\nprotocol: x.y.z`. Now we’re inventing a custom non-standard key-value format. This is obviously not DRY and not preferable in my view.
2. We expose _additional endpoint_ that exposes just `Zold::PROTOCOL` and keep `GET /versión` intact. That’s better, but we end up with unnecessary endpoints.
3. `GET /version` returns `{"version": "a.b.c", "protocol": "x.y.z"}`. This is my suggestion. We ended up with less complexity and therefore more maintainable code.

And imagine we switch from a server-side generate app to say React.js. If we stuck to JSON, it'll be easier to implement than both option 1 and 2.

And we don't have to deal with bugs such as #36: even though one must encode/decode JSON, lack of doing so will make the code _always fail immediately_ as they are of a different type. It's not a string that we might or might not have forgotten to decode, it's either a structure such as Hash or Array or it's a String.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@botanicus we are using JSON everywhere, except some very basic/primitive end points, which return plain text. Those are `/version` and in the future `/protocol`. In other words, our API is in JSON, but the front-end has supplementary plain text entry points, mostly for fun.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#42` is not assigned, can't get performer
