### ISSUE TITLE
0.31.5

### ISSUE THREAD

**Issue by davvd** [zold-io/wts.zold.io#424]

**Comment by davvd** [comment]
@rultor release tag = `0.41.9`

**Comment by davvd** [comment]
@rultor release tag = `0.41.9`

**Comment by davvd** [comment]
@rultor release tag = `0.41.9`

**Comment by davvd** [comment]
@rultor stop

**Comment by davvd** [comment]
@rultor release tag = `0.41.9`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#424` is not assigned, can't get performer
