### ISSUE TITLE
Use REST

### ISSUE THREAD

**Issue by botanicus** [zold-io/wts.zold.io#43]
[REST](https://en.m.wikipedia.org/wiki/Representational_state_transfer) is the standard in web development.

In REST rather than `POST /do-pay` we should `POST /payments`. The HTTP verb `POST` in REST is to create entities in given resource. The resource is `/payments`. It says "create new instance of the payments class" essentially. _In a way REST is OOP of the web._

The advantages are:
- You don't have to guess where to find things. If you know name of the resource, you know what `GET/POST/PUT` does.
- Developers know and expect REST.
- There are many tools available, so less work might be required than with the RPC-style syntax such as `/do-pay`.

**Comment by 0crat** [comment]
Job [#43](https://github.com/zold-io/wts.zold.io/issues/43) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
The job [#43](https://github.com/zold-io/wts.zold.io/issues/43) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CB28FH2NR/021f4b24-ac74-4445-95a7-703f5ae496bb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@botanicus not a bad idea, but it will require more coding on the server side. Now our Web UI is the same as our HTTP API, same entry points, same URIs. So, we say no to the full REST :)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/wts.zold.io/issues/43#issuecomment-476215366))

@yegor256 Job `gh:zold-io/wts.zold.io#43` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#43` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#43](https://github.com/zold-io/wts.zold.io/issues/43) is now out of scope
