### ISSUE TITLE
Node score value equal to 1-0

### ISSUE THREAD

**Issue by NoxFP** [zold-io/wts.zold.io#50]
Recently checked after long time the node I have up for more than 2 weeks: http://80.211.62.201:4096/
value was always 1, even one time 0 which was weird, cuz when the node was installed score was 13-14. I reseted the vps to try "Restart" things up and I end up not even finding the vps anymore, do I have to reinstall everything again ?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@noxfp[/z](https://www.0crat.com/u/noxfp) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@NoxFP 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#50` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
