### ISSUE TITLE
fund by...

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#52]

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#52` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.1`
