### ISSUE TITLE
Once you sign-up, you will receive a bonus of 8 ZLD to your wallet.

### ISSUE THREAD

**Issue by stepan-romankov** [zold-io/wts.zold.io#53]
1. Haven't received it. Does some time should gone before I receive it?
Wallet ID: f699ea4fc18a8114

2. I also started a node but don't see it in https://wts.zold.io/remotes, any ideas why?
Node address: http://62.113.238.236:4096

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#53` is not assigned, can't get performer
