### ISSUE TITLE
Receiver field size is too small (16 symbols) on payment page

### ISSUE THREAD

**Issue by stepan-romankov** [zold-io/wts.zold.io#55]
https://wts.zold.io/pay 
'_Send ZLD to (either wallet ID or GitHub login):_' field is to small. E.g. when I was testing it with account '**@stepan-romankov-2**' I wasn't able to write it down, it was cut off as '**@stepan-romankov**'.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@stepan-romankov[/z](https://www.0crat.com/u/stepan-romankov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@stepan-romankov fixed, thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#55` is not assigned, can't get performer
