### ISSUE TITLE
Missing documentation on Maven

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/wts.zold.io#57]
After cloning the repo, I followed the steps provided on documentation but received an error on a missing _mvn_ command.

Apparently _Apache Maven_ is a prerequisite to run all tests, and I think that should clearly reported in the README file

**Comment by yegor256** [comment]
@emilianodellacasa thanks, fixed!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
