### ISSUE TITLE
update version - no remotes caused by lower version

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/wts.zold.io#61]
The `wts.zold.io` nodes uses the option `--no-reboot` and will drop nodes caused by his lower version number. This will lead to a constant remote entry of `b1.zold.io` and count of 1, which isn't helping for pulling or pushing wallets.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by oltdaniel** [comment]
@yegor256 actually, this is a general issue in the node code. Will move it to the main repo

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#61` is not assigned, can't get performer
