### ISSUE TITLE
All nodes have huge number of errors

### ISSUE THREAD

**Issue by stepan-romankov** [zold-io/wts.zold.io#64]
https://wts.zold.io/remotes

<img width="444" alt="screen shot 2018-08-25 at 15 53 24" src="https://user-images.githubusercontent.com/1895302/44618900-0ac81d80-a87f-11e8-998e-1403cdab76e3.png">

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@stepan-romankov[/z](https://www.0crat.com/u/stepan-romankov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@stepan-romankov should be OK now

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#64` is not assigned, can't get performer
