### ISSUE TITLE
Hosting Bonuses not distributed

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/wts.zold.io#65]
Since end of August apparently hosting bonuses are not distributed, let's fix this

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@emilianodellacasa this seems to be connected to this issue, but I'm not sure yet: https://github.com/zold-io/zold/issues/479 Investigating...

**Comment by yegor256** [comment]
@emilianodellacasa seems to be fixed

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#65` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
