### ISSUE TITLE
Can't see some payments via API

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#66]
0crat sens me extra zold payments via wts API without errors (API returns `303` HTTP status), but I can see only one transaction in my wallet.

`Send zold` claims: https://www.0crat.com/footprint/CA2075Q49/2561345126 https://www.0crat.com/footprint/CA2075Q49/2561346154

wallet id: `3be3416c805e4371`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#66](https://github.com/zold-io/wts.zold.io/issues/66) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

Check `/output?id=...` for full logs of each payment operation

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#66` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#66](https://github.com/zold-io/wts.zold.io/issues/66) is now out of scope
