### ISSUE TITLE
Missing validation on keygap input in https://wts.zold.io/api

### ISSUE THREAD

**Issue by filfreire** [zold-io/wts.zold.io#69]
In https://wts.zold.io/api the user is able to submit an empty string in the keygap input field, or another completely different string, and will still get successfully to the API token screen.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@filfreire fixed, thanks for reporting

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#69` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
