### ISSUE TITLE
The /do-api page could display a curl request for ease of use

### ISSUE THREAD

**Issue by filfreire** [zold-io/wts.zold.io#70]
Currently the /do-api returns this text as a code snippet:
```
POST /do-pay HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: wts.zold.io
X-Zold-Wts: XXXXXXX

bnf=yegor256&amount=19.99&details=For+the+pizza&keygap=XXXXXXX

```

When instead it could return a `curl` request ready to be copied, changed a bit, and used in the shell.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@filfreire seems to be fixed, thanks!
