### ISSUE TITLE
503 error on API call

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#74]
0crat is not able to send Zold via API because of 503 error for `POST /do-pay`: https://sentry.io/zerocracy/farm/issues/714507585/?query=is%3Aunresolved

**Comment by yegor256** [comment]
@g4s8 are you sure the link is correct?

**Comment by yegor256** [comment]
@g4s8 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#74` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
