### ISSUE TITLE
BTC to ZLD gate do not work

### ISSUE THREAD

**Issue by tt1403936** [zold-io/wts.zold.io#76]
There is an error nn Buy/Sell tab

Internal error at 0.0.0

Please help us improve our service and submit the following stacktrace to our GitHub repo :

RuntimeError: Can't create Bitcoin address for @: Bad Gateway
	/app/objects/btc.rb:46:in `create'
	/app/wts.rb:361:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@tt1403936 fixed in 4eb7812823ceb034534961918a64463df2d7d572 Just refresh the page please.

**Comment by 0crat** [comment]
Thanks for your contribution, @tt1403936[/z](https://www.0crat.com/u/tt1403936)! If you would be a member of [the project](https://www.0crat.com/p/CB28FH2NR), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#76](https://github.com/zold-io/wts.zold.io/issues/76) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB28FH2NR/29347346-0a11-472b-a612-6e20c0b9593c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#76` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by tt1403936** [comment]
Now the sam error on green line and without a stack

Can't create Bitcoin address for @tt1403936, try again: Bad Gateway

"Bad gateway" is a connectivity issue I guess not a typo

**Comment by yegor256** [comment]
@tt1403936 yes, there is some issue with blockchain.com. Can you just try again?

**Comment by tt1403936** [comment]
the same error. blockchain.info api docs says that there is a limit of 20 generated unused addresses. May be thats the case, try to pass another parameter gap_limit to api.blockchain.info. Strange error though, it must be something understandable from them.

**Comment by yegor256** [comment]
@tt1403936 I did in 36b14ee2104223de83f3d6811dcfda7e80a0ebf3, try again

**Comment by tt1403936** [comment]
Nope. other error now 

nternal error at 0.0.0

Please help us improve our service and submit the following stacktrace to our GitHub repo :

TypeError: no implicit conversion of Integer into String
	/app/objects/btc.rb:46:in `escape'
	/app/objects/btc.rb:46:in `block in create'
	/app/objects/btc.rb:46:in `each'
	/app/objects/btc.rb:46:in `map'
	/app/objects/btc.rb:46:in `create'
	/app/wts.rb:357:in `block in <top (required)>'

**Comment by yegor256** [comment]
@tt1403936 fixed, try again

**Comment by tt1403936** [comment]
Now it works, thanks. Lets try to exchange :)

**Comment by 0crat** [comment]
The job [#76](https://github.com/zold-io/wts.zold.io/issues/76) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
