### ISSUE TITLE
What does the debt is 0.02ZLD mean?

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/wts.zold.io#78]
```
Wallet ID: e560c4fb95684c6d
Balance: 7.43452381 ZLD (31931036624 zents)
Transactions: 59
Taxes: 0.00ZLD paid, the debt is 0.02ZLD
File size: 6Kb
Modified: 2018-12-11T08:55:22Z (13m ago)
```
The `Taxes: 0.00ZLD paid, the debt is 0.02ZLD` message is not clear enough. What is the `debt` here? Does this mean that the `debt` amount was not charged as a `tax` or that amount was not debited for some reasons? What may these reasons be?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by denis-konovalyenko** [comment]
The debt value has changed to `0.03ZLD` for some reasons (see below):
```
Wallet ID: e560c4fb95684c6d
Balance: 7.43452381 ZLD (31931036624 zents)
Transactions: 59
Taxes: 0.00ZLD paid, the debt is 0.03ZLD
File size: 6Kb
Modified: 2018-12-25T13:34:51Z (9.69s ago) 
```

**Comment by yegor256** [comment]
@denis-konovalyenko I believe it's explained now

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#78` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
