### ISSUE TITLE
Why the date is now shown as an interval in hours?

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/wts.zold.io#79]
```
ID | Amount | Date | Beneficiary | Details
- | 0.12 | 31h | 17737fee5b825835 | Hosting bonus for 91.211.13.180 4096 20

```
It is quite difficult to calculate the actual timestamp manually. Thus, it is not user-friendly any more. Would it be possible to revert to the previously shown values?

**Comment by yegor256** [comment]
@denis-konovalyenko you can move the mouse over the "31h" and you will see the actual ISO-8601 date.

**Comment by denis-konovalyenko** [comment]
@yegor256 , thanks for responding!

I am afraid, it is still embarrassing. I need to move the mouse pointer over every entry in the list. How about making this vice versa - printing the actual ISO-8601 dates and showing hours on hovering? It is more significant to see the transaction timestamps rather than how much time has flown since the actual transaction occurred.

**Comment by denis-konovalyenko** [comment]
@yegor256 , one more thing on that. In any way you decide to go on with this, could you please take care about the conistensy among the list label and its data. I.e. "Date" with ISO-8601 date or "Interval since the transaction occurred" (or something better) with hours?

Thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#79` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
