### ISSUE TITLE
It's possible to sell ZLD without key gap

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#85]
Steps to reproduce:
 1. Go to [buy/sell](https://wts.zold.io/btc) page
 2. Enter valid amount (e.g. $1) and valid BTC address
 3. Enter `00000000` as a key gap
 4. Submit query

Expected: wts should not send BTC if key gap is not correct

Actual: wts sent BTC and show this exchange in transactin

```
ZLD exchange to 0.0002724499 BTC
at 15mP4LQQZN6AUz8u­jz4KHBFoDnLGSbEM­iE,
price is 3303.36 
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#85` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
