### ISSUE TITLE
auto pull wallet when user do login

### ISSUE THREAD

**Issue by blackout314** [zold-io/wts.zold.io#87]
auto pull wallet when user do login, is more user friendly and have less cost to implement

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@blackout314 this won't be obvious for a user -- why it's happening and what is in the log. We won't do this.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#87` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
