### ISSUE TITLE
ZLD to BTC gate not working

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/wts.zold.io#88]
Today I tried several times to exchange ZLD for BTC to test issue #86, but it never worked

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@emilianodellacasa please attach your logs

**Comment by emilianodellacasa** [comment]
I think this is the reason:

ERROR: RuntimeError: Can't read RSA key (Neither PUB key nor PRIV key: nested asn1 error)
/app/vendor/bundle/ruby/2.5.0/gems/zold-0.18.9/lib/zold/key.rb:90:in `rescue in rsa'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.18.9/lib/zold/key.rb:87:in `rsa'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.18.9/lib/zold/key.rb:62:in `to_s'
	/app/objects/item.rb:66:in `key'
	/app/objects/ops.rb:82:in `block in pay'
	/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tempfile.rb:295:in `open'
	/app/objects/ops.rb:81:in `pay'
	/app/wts.rb:461:in `block (2 levels) in <top (required)>'
	/app/wts.rb:635:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/versioned_job.rb:34:in `call'
	/app/objects/safe_job.rb:34:in `call'
	/app/objects/async_job.rb:46:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:124:in `block in open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/objects/async_job.rb:45:in `block in call'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

**Comment by blackout314** [comment]
```
ERROR: TypeError: no implicit conversion of nil into String
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/clean.rb:58:in `join'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/clean.rb:58:in `block in run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/clean.rb:57:in `each'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/clean.rb:57:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/pull.rb:46:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/invoice.rb:72:in `invoice'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/invoice.rb:64:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/pay.rb:79:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.19.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/objects/ops.rb:76:in `block in pay'
	/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tempfile.rb:295:in `open'
	/app/objects/ops.rb:73:in `pay'
	/app/wts.rb:463:in `block (2 levels) in <top (required)>'
	/app/wts.rb:639:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/clean_job.rb:39:in `call'
	/app/objects/versioned_job.rb:34:in `call'
	/app/objects/safe_job.rb:34:in `call'
	/app/objects/async_job.rb:46:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:124:in `block in open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/objects/async_job.rb:45:in `block in call'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by yegor256** [comment]
@emilianodellacasa This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#88` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
