### ISSUE TITLE
Beneficiary infomation is not always relevant

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/wts.zold.io#89]
The wallet information page lists transactions the following way (example):
```
ID | Amount | Date | Beneficiary | Details
- | 0.12 | 371h | 17737fee5b825835 | Hosting bonus for 91.211.13.180 4096 20
```
where `Beneficiary` column may contain not only the beneficiary's wallet information but correspondent's as well. My wallet ID is `e560c4fb95684c6d`, for instance.

Would it be possible to add a new column to state the correspondent account (wallet) information or change the `Beneficiary` label to something better?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@denis-konovalyenko fixed in 2f79953 thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#89` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
