### ISSUE TITLE
print BTC balance to Telegram

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#91]
Let's print it out, after each BTC transaction.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#91` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#103](https://github.com/zold-io/wts.zold.io/issues/103) is still not solved.
